### ISSUE TITLE
Feedback from initial API Review

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#112]
## Summary

We had an API review and here are the list of changes we need to make:

- [x] Remove constructors from HttpContext, HttpRequest, HttpResponse https://github.com/dotnet/systemweb-adapters/pull/113
- [ ] ~~Add [Obsolete] to APIs that will cause sync over async and expose async counterparts on the ASP.NET Core build https://github.com/dotnet/systemweb-adapters/issues/164~~
- [x] Move builders to `System.Web` namespace for framework helpers and `Microsoft.AspNetCore.Builders` for the core helpers
- [x] Remove interfaces from attributes https://github.com/dotnet/systemweb-adapters/pull/113
- [x] Rename IsEnabled to IsDisabled from metadata attributes https://github.com/dotnet/systemweb-adapters/pull/113
- [x] Rename PreLoad to Preload https://github.com/dotnet/systemweb-adapters/pull/113
- [x] Make DelegatingSessionState internal (https://github.com/dotnet/systemweb-adapters/pull/134)
- [x] Make DefaultRequestHeadersToForward and DefaultResponseHeadersToForward internal (https://github.com/dotnet/systemweb-adapters/pull/120)
- [x] #138
- [x] AuthenticationEndpointPath should be a PathString on ASP.NET Core. (https://github.com/dotnet/systemweb-adapters/pull/120)
- [x] Avoid using the same name for types that are at all structurally different and will not ever have shared code calling it from top (https://github.com/dotnet/systemweb-adapters/pull/120)
- [ ] Rethink builder pattern for remote app functionality (https://github.com/dotnet/systemweb-adapters/pull/120 https://github.com/dotnet/systemweb-adapters/pull/165)

Original feedback:

- https://github.com/dotnet/aspnetcore/issues/42090
- https://github.com/dotnet/aspnetcore/issues/42091
- https://github.com/dotnet/aspnetcore/issues/42092

**Comment by mjrousos** [comment]
Yea, I can make the namespace chances in #110. I'll get that updated tomorrow.

**Comment by mjrousos** [comment]
For the .NET Core namespace for the extension methods, should it be `Microsoft.AspNetCore.Builders` or `Microsoft.Extensions.DependencyInjection`? The extension methods start by extending `IServiceCollection` (rather than by extending the web application builder directly).

**Comment by twsouthwick** [comment]
`Microsoft.AspNetCore.Builders` - that's the pattern ASP.NET Core wants us to use

**Comment by mjrousos** [comment]
Hm... ok. It seems like a lot of the other builders are using MED (`AddControllers`, `AddReverseProxy`, etc.) but I'll use Microsoft.AspNetCore.Builders for now and we can ask about it.

**Comment by adityamandaleeka** [comment]
cc @mjrousos for "NetworkTimeout could probably be made an HttpClient"

**Comment by adityamandaleeka** [comment]
Looks like the only one remaining is 

> Add [Obsolete] to APIs that will cause sync over async and expose async counterparts on the ASP.NET Core build https://github.com/dotnet/systemweb-adapters/pull/136

**Comment by danroth27** [comment]
> Add [Obsolete] to APIs that will cause sync over async and expose async counterparts on the ASP.NET Core build

Which APIs are we talking about obsoleting? Are we talking about APIs in the System.Web Adapters? We haven't shipped a stable release of the System.Web Adapters package yet, so if we need to make an API change we can just do so without obsoleting anything.

**Comment by twsouthwick** [comment]
@danroth27 this is about providing a pathway for users using APIs that are currently doing sync over async due to the shape of System.Web APIs. We would need to keep the APIs themselves, but the obsolete would identify what they should use instead. This was an item that was not necessary initially (and does not block us from releasing). I've created a separate issue to discuss what we should do here: https://github.com/dotnet/systemweb-adapters/issues/164

**Comment by twsouthwick** [comment]
Found a type we missed to update. Reopening until https://github.com/dotnet/systemweb-adapters/pull/165 is merged
