### ISSUE TITLE
HTTPS server variable is set to upper case "ON" causing .NET framework to return false for request.IsSecure

### ISSUE THREAD

**Issue by ragnarstolsmark** [dotnet/systemweb-adapters#125]
### Describe the bug
.NET framework returns wrong request.url when the request hitting the proxy was transferred over https.

### To Reproduce

1. Serve the .NET Framework app over http
2. Add the following to global asax 
```csharp
SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
	.AddProxySupport(options => options.UseForwardedHeaders = true );
```
3. Access the proxy over https.
5. In the .NET framework app print out HttpContext.Current.Request.Url
6. It should start with https://
7. It starts with http.
### Further technical details 
This is happening in the latest nightly build. 
Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc):
- .NET Framework Version: .NET Framework 4.8
- IIS Version: 10
- Windows Version: 10

*ASP.NET Core Application*:
- Targeted .NET version: .NET 6
- .NET SDK version: 6.0.302

**Comment by twsouthwick** [comment]
Fixed in #126.

Thanks @ragnarstolsmark for catching this and fixing it!
