### ISSUE TITLE
Preview3 adds dependencies which (Could) break .NET Framework webapps

### ISSUE THREAD

**Issue by tbertenshaw** [dotnet/systemweb-adapters#127]
### Describe the bug
After upgrading my Netframework app (which is  using Microsoft.AspNetCore.SystemWebadapters for auth) breaks with various missing component dependencies which werent required in Preview2.

as seen https://www.nuget.org/packages/Microsoft.AspNetCore.SystemWebAdapters/1.0.0-preview.3.22370.2#dependencies-body-tab

### Exceptions (if any)
`Could not load file or assembly Microsoft.Bcl.AsyncInterfaces`

If i add that and a binding direct to webconfig, then missing 
`Unable to load System.Threading.Tasks.Extensions`

if i add a binding direct to that then various other DI issues with incompatabile components.

Hopefully this can be resolved? The  main reason for using this package is to get around incompatabile dependaancy versions when i tried to update the project components in order to prepare for Core upgrade.

**Comment by tbertenshaw** [comment]
I managed to Fix my implementation by 

installing  `Microsoft.Bcl.AsyncInterfaces` version `6.0.0`

adding the following to `web.config`

```xml
	<dependentAssembly>
		<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
	</dependentAssembly>
	<dependentAssembly>
		<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
	</dependentAssembly>
	<dependentAssembly>
		<assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
	</dependentAssembly>

```

**Comment by twsouthwick** [comment]
Opened an issue to rethink the package layering to minimize these kind of issues
