### ISSUE TITLE
Relayer packages to minimize dependencies

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#131]
## Summary

We should relayer packages to keep the core adapters (i.e. System.Web types) an isolated package, and the supporting infrastructure as a separate layer.

## Motivation and goals

The adapters need to use some external dependencies for some functionality (i.e. dependency injection, JSON serialization, etc) but that is mostly at the level of tying the services together. Specifically, this is only needed for middleware and modules that don't affect the core System.Web types that are being adapted.

In large projects (especially those with packages.config), adding dependencies low down in the stack can have undesired consequences from binding redirects to challenges with keeping versions in check (i.e. early in the process when still using packages.config). In order to help with this, we can isolate the core adapters from the infrastructure to remove any external dependencies from the adapter layer and hence the package used in supporting libraries.

![RelayerPackages](https://user-images.githubusercontent.com/583206/181123492-987fd175-c6db-4535-8e8c-4453d8d2aba6.png)

## In scope

- Move all the non-System.Web types to a separate assembly. Potentially `Microsoft.AspNetCore.SystemWebAdapters.Extensions`
- Retain required interfaces (only ones identified at this point is `IBufferedResponseFeature` and `ISessionState`) in the core assembly

## Out of scope

- None

## Risks / unknowns

This will be a breaking change for how people consume the project, but will help prevent issues such as #127.

**Comment by twsouthwick** [comment]
@adityamandaleeka @danroth27 Thoughts (especially around the new package name)?

**Comment by khellang** [comment]
Why don't you flip the naming and call the packages something like ``Microsoft.AspNetCore.SystemWeb.Adapters` and `Microsoft.AspNetCore.SystemWeb.Shims`. i think it matches the actual content of the packages better.
