### ISSUE TITLE
Auth: Share cookies between Framework and Core apps

### ISSUE THREAD

**Issue by mjrousos** [dotnet/systemweb-adapters#14]

**Comment by mjrousos** [comment]
Related abandoned draft PR: #18

**Comment by HaoK** [comment]
Done as part of https://github.com/dotnet/systemweb-adapters/pull/121

**Comment by HaoK** [comment]
Leaving this open to track adding a few more helpers that discussed in https://github.com/dotnet/systemweb-adapters/pull/121

**Comment by adityamandaleeka** [comment]
Due to the Owin concerns, we'll skip this for RC1. Based on demand for this and other Owin-related things in the future we can consider a package like SystemWebAdapters.Owin or something.

**Comment by Tratcher** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/21987#issuecomment-821132315

**Comment by danroth27** [comment]
> Leaving this open to track adding a few more helpers that discussed in #121

We decided that we don't want to add new APIs for this but we do want to make sure the scenario is properly documented.
