### ISSUE TITLE
Add HttpRequestBase.Files and supporting types

### ISSUE THREAD

**Issue by sdekock** [dotnet/systemweb-adapters#141]
In PR https://github.com/dotnet/systemweb-adapters/pull/103 the types to handle file upload were added: Files property on HttpRequest and HttpPostedFile class.

These should also be created in the *Base variants: Files property in HttpRequestBase and a HttpPostedFileBase class.

**Comment by sdekock** [comment]
To be considered as part of #91 ?

**Comment by twsouthwick** [comment]
Let's keep it separate - #91 will be separated out into new issues (all features from that that will be addressed for v1 have been at this point). Can you share the full API shape you want to enable here?

**Comment by sdekock** [comment]
> Can you share the full API shape you want to enable here?

The [Files property on the HttpRequestBase](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequestbase.files) class
And supporting types:
[HttpFileCollectionBase](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpfilecollectionbase)
[HttpFileCollectionWrapper](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpfilecollectionwrapper)
[HttpPostedFileBase](https://docs.microsoft.com/en-us/dotnet/api/system.web.httppostedfilebase)
[HttpPostedFileWrapper](https://docs.microsoft.com/en-us/dotnet/api/system.web.httppostedfilewrapper)

Same functionality that was exposed as per PR https://github.com/dotnet/systemweb-adapters/pull/103 on HttpRequest, but then on the HttpRequestBase variant.

I already made an attempt of implementing this here: https://github.com/dotnet/systemweb-adapters/compare/main...sdekock:systemweb-adapters:sdk/requestbase-files
But I have not been able to test it, so I have not yet created a PR. I can finish it if you want to ...

**Comment by adityamandaleeka** [comment]
@sdekock Sure, a PR would be welcomed. At this point it likely wouldn't make it into the RC 1 release but we would get it into post-1.0.
