### ISSUE TITLE
Enable HttpRequest.ReadEntityBodyMode/GetBuffer[ed|less]InputStream()

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#150]
## Summary

This adds the ability to know what state the request stream is in (i.e. buffered, not buffered, read, etc)

## In scope

- `System.Web.ReadEntityBodyMode`
- `System.Web.HttpRequest.ReadEntityBodyMode`
- `System.Web.HttpRequest.GetBufferlessInputStream()`
- `System.Web.HttpRequest.GetBufferedInputStream()`

**Comment by Maples7** [comment]
Adding a related discussion [here](https://github.com/dotnet/aspnetcore/issues/43084).
