### ISSUE TITLE
Using Microsoft.AspNetCore.SystemWebAdapters, Yarp is throwing ArgumentException: Invalid destination prefix. (Parameter 'destinationPrefix')

### ISSUE THREAD

**Issue by ztepsic** [dotnet/systemweb-adapters#158]
Hi,

I'm trying to use Microsoft.AspNetCore.SystemWebAdapters to implement a incremental move from a big existing ASP.NET MVC site to a ASP.NET Core MVC site. I was following steps from the article https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/, but once I request a route which should be forwared to the old ASP.NET MVC site I'm getting the following exception:
```
System.ArgumentException: Invalid destination prefix. (Parameter 'destinationPrefix')
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
   at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
   at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I saw on stachoverflow that someone has the same issue: https://stackoverflow.com/questions/73401019/trying-to-implement-microsoft-aspnetcore-systemwebadapters-between-a-asp-net-mvc but there is not any solution nor any comments.

I tried the same steps from the article on the new basic ASP.NET MVC project and there it works OK. 

So, it seems that there is something on the big existing ASP.NET MVC project that is causing "System.ArgumentException: Invalid destination prefix. (Parameter 'destinationPrefix')" Yarp exception, but I cannot find what and where is the problem. Can anybody help?

**Comment by twsouthwick** [comment]
Can you share what your `appsettings.json` and `launchsettings` are? It looks like YARP isn't getting a fallback address (the samples in the repo set it as an env variable here: https://github.com/dotnet/systemweb-adapters/blob/main/samples/MvcCoreApp/Properties/launchSettings.json#L16).

**Comment by ztepsic** [comment]
I found where is the problem and it is related to appsettings.json.

In Program.cs I'm doing this

```c#
builder.Host.ConfigureAppConfiguration((hostingContext, configBuilder) => {
    IHostEnvironment env = hostingContext.HostingEnvironment;
    configBuilder
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true)
}

```

Problematic line is ` .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)` which causes that ReverseProxy is not configured fore some reason.

Once I removed this problematic line that it worked.

**Comment by twsouthwick** [comment]
If you share the contents of each of those files we can probably pinpoint the issue

**Comment by ztepsic** [comment]
Files are simple ones:

`appsettings.json`
```json
{
 "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },

  "AllowedHosts": "*",

  "ConnectionStrings": {
    "DbConnectionString": "DatabaseConnectionStringPlaceholder",
    "AzureStorageConnectionString": "AzureStorageConnectionStringPlaceholder"
  },

  "WebOptimizer": {
    "EnableCaching": true,
    "EnableTagHelperBundling": true
  },

  "ReverseProxy": {
    "Routes": {
      "fallbackRoute": {
        "ClusterId": "fallbackCluster",
        "Order": "1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
    "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": ""
          }
        }
      }
    }
  }
}
```

`appsettings.Test.json`
```json
{
   "Logging": {
    "LogLevel": {
      "Default": "Debug",
    }
  },

  "ConnectionStrings": {
    "DbConnectionString": "some-value",
    "AzureStorageConnectionString": "some-value"
  },

  "WebOptimizer": {
    "EnableCaching": false,
    "EnableTagHelperBundling": false
  }

}
```

So, If I comment the line where I'm trying to add "appsettings.json" then everything is working OK:
```c#
builder.Host.ConfigureAppConfiguration((hostingContext, configBuilder) => {
    IHostEnvironment env = hostingContext.HostingEnvironment;
    configBuilder
//                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true)
}

````

If the line `  .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)` is uncommented, it seems that it overrides values that are set either by Yarp or systemwebadapters during initialization before calling the `.AddJsonFile` in my code.

**Comment by twsouthwick** [comment]
This appears to be happening then because you are registering a destination, but don't have the path set. If you comment that out, I'd be surprised if you see any traffic going to the framework app.

Can you describe what your set up is trying to do? YARP is used here generally to forward requests onto the backend framework app. Is that what you're doing? If so, I don't see any configuration where that is configured. 

Can you also share your launchsettings.json?

/cc @tratcher in case there's something here re: YARP I'm not aware of

**Comment by Tratcher** [comment]
You have to set the Address field, either in the appsettings or launchsettings.
```
    "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": ""
          }
        }
      }
```
https://github.com/dotnet/systemweb-adapters/blob/main/samples/MvcCoreApp/Properties/launchSettings.json#L16

**Comment by twsouthwick** [comment]
@Tratcher The error message is a little confusing here. Is this something that could be fixed in YARP to be clear that there is no address set?

**Comment by ztepsic** [comment]
> This appears to be happening then because you are registering a destination, but don't have the path set. If you comment that out, I'd be surprised if you see any traffic going to the framework app.
> 
> Can you describe what your set up is trying to do? YARP is used here generally to forward requests onto the backend framework app. Is that what you're doing? If so, I don't see any configuration where that is configured.
> 
> Can you also share your launchsettings.json?
> 
> /cc @Tratcher in case there's something here re: YARP I'm not aware of

I was using "Microsoft Project Migrations" extension which generated code and filled appsettings.json and launchesttings.json.
The part for RemoteProxy in appsettings.json I provided above is what that plugin generated.

Initially it loads values from launchsettings.json (env variables), but if I load appsettings.json (with `.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)`) after that then `ReverseProxy:Clusters:failbackCluster:Destinations:fallbackApp:Address` value is run over with empty value from appsettings.json.

It was my mistake to load appsettings.json and run over environment variable values, but as you said error message was confusing and didn't know where to look for the cause.

**Comment by twsouthwick** [comment]
oh yes, that makes sense. Why are you reloading the appsettings.json? That should be loaded by default, followed by env settings (see https://source.dot.net/#Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.cs,224)

**Comment by adityamandaleeka** [comment]
Triage: let's comment out the fallback app config (something like this but you'll have to check the comment style):

```json
    "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          // "fallbackApp": {
          //   "Address": ""
          // }
        }
      }
```

**Comment by adityamandaleeka** [comment]
@abpiskunov ^
