### ISSUE TITLE
System.Web typeload exception in class library

### ISSUE THREAD

**Issue by sanjuroo** [dotnet/systemweb-adapters#160]
I am trying to migrate some old API to .net 6. Just to verify when I use HttpContext.Current in .net 6 API project everything is fine.

Problem is that one of the older class library projects in solution is using HttpContext.Current also. Target framework of this class lib is net472. I removed System.Web reference, added reference to Microsoft.AspNetCore.SystemWebAdapters. I cleaned project, deleted bin/obj folders. When this lib is consumed it throws typeloadexception Could not load type 'System.Web.HttpContext' from assembly 'System.Web, Version=4.0.0.0'.

How should i migrate class libraries?

**Comment by khellang** [comment]
Are you trying to consume a `net472` class library in a `net6.0` app? Is that even possible? I suggest converting your class library to `netstandard2.0` first.

**Comment by twsouthwick** [comment]
If you're using the net472 output, it will look in `System.Web.dll` for the implementation of `HttpContext`. Please add a target for `net6.0` or `netstandard2.0` to your project file. For an example, see https://github.com/dotnet/systemweb-adapters/blob/main/samples/ClassLibrary/ClassLibrary.csproj#L4
