### ISSUE TITLE
Update Arcade toolchain

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#167]
We're still on .NET 7 Preview 2. @Tratcher how do we update? Is it something that can be automated?

**Comment by Tratcher** [comment]
It can be updated and automated with the darc tool. Is there a specific/urget reason you need an update?

**Comment by twsouthwick** [comment]
I noticed build warnings about using deprecated agents at https://dev.azure.com/dnceng/public/_build/results?buildId=1964552&view=results and then noticed that we're behind on Arcade updates. These agents are getting brownouts to notify us we need to get off of them. I've only seen one failure so far, but would be good to update.

**Comment by Tratcher** [comment]
I've enabled weekly updates via darc. The first one is https://github.com/dotnet/systemweb-adapters/issues/167.
