### ISSUE TITLE
Remote authentication not working when Framework app is not the root of the website

### ISSUE THREAD

**Issue by pdunkerley** [dotnet/systemweb-adapters#191]
I am trying to get the remote authentication working against our ASP.NET MVC 5.2 app. Our app doesn't run in the root of the IIS website - we have to run it as a sub application (i.e. /myapp), and I think this may be causing the problem I am having. Essentially, when the Core app makes the authentication request to the Framework app, it calls "/systemweb-adapters/authenticate" and not "/myapp/systemweb-adapters/authenticate", which then fails with a 404 (I can see this in the IIS logs).

In Program.cs I have the following:

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSystemWebAdapters()
    .AddRemoteApp(options =>
    {
        options.RemoteAppUrl = new("http://localhost/MyApp");
        options.ApiKey = "MySecretKey";
    })
    .AddRemoteAppAuthentication(true);
```

But it seems to ignore the "/MyApp" bit when it makes the request. I have created a dummy solution with a framework app and a core app, and can get the remote authentication working just fine when the framework app is in the root of a website, but as soon as I put it in a sub folder, it fails due to the above path problem.

Is this a bug, or I am approaching this incorrectly?

**Comment by twsouthwick** [comment]
Nope, that should be fine. It was partially fixed in #139, then regressed in #178. This is now handled for any remote call, and will also correctly compare on the backend in cases like this (#139 did not handle that case).

**Comment by twsouthwick** [comment]
Also, please note the following guideline if you're using app or virtual directories: https://github.com/dotnet/systemweb-adapters/blob/main/docs/usage_guidance.md#virtual-directories-must-be-identical-for-framework-and-core-applications

**Comment by Apeksha21** [comment]
> Also, please note the following guideline if you're using app or virtual directories: https://github.com/dotnet/systemweb-adapters/blob/main/docs/usage_guidance.md#virtual-directories-must-be-identical-for-framework-and-core-applications

This link is broken. Please share updated source for this info. I am facing a similar issue.

**Comment by twsouthwick** [comment]
Since I commented, docs were moved to official page: https://learn.microsoft.com/aspnet/core/migration/inc/usage_guidance#virtual-directories-must-be-identical-for-framework-and-core-applications
