### ISSUE TITLE
'HttpApplicationState' does not contain a definition for 'AddSystemWebAdapters'

### ISSUE THREAD

**Issue by br3nt** [dotnet/systemweb-adapters#199]
### Describe the bug

I am getting the error:

> 'HttpApplicationState' does not contain a definition for 'AddSystemWebAdapters' and the best extension method overload 'SystemWebAdapterConfiguration.AddSystemWebAdapters(HttpApplication)' requires a receiver of type 'HttpApplication'

I am trying following along to the instructions provided in the following places:

* https://github.com/dotnet/systemweb-adapters/blob/v1.0.0-preview.3/docs/framework.md
* https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/comment-page-2/#proxy-support

I have add the `Microsoft.AspNetCore.SystemWebAdapters` to my ASP.NET Framework project. \
I assume this is required, but is not explicitly stated in the two documents linked above.

I have added the following code to `MvcApplication.Application_Start()` in the ASP.NET Framework project:

```c#
using Microsoft.AspNetCore.SystemWebAdapters;

namespace MyFrameworkMvcApp
{
    public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            Application
                .AddSystemWebAdapters()
                .AddProxySupport(options => options.UseForwardedHeaders = true);
        }
    }
}
```

I get:

![image](https://user-images.githubusercontent.com/1089651/189792384-db6a55b4-07b2-4419-aa7a-fddb2296cfd8.png)

And I don't get any suggestions of additional packages to add:

![image](https://user-images.githubusercontent.com/1089651/189792506-215fc135-5733-459b-aca0-147dad94fc62.png)

### To Reproduce

Described above.

### Exceptions (if any)

N/A

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used: MVC
- .NET Framework Version: 4.8
- Windows Version: 10

**Comment by br3nt** [comment]
I noticed that in [this SO question](https://stackoverflow.com/q/73401019/848668) the author is using 

```

SystemWebAdapterConfiguration
    .AddSystemWebAdapters(this)
    .AddProxySupport(options => options.UseForwardedHeaders = true);=
```

I have added this an it doesn't raise any warnings.

So, can I use that above code in replacement of what's in the documentation?:

```
Application
    .AddSystemWebAdapters()
    .AddProxySupport(options => options.UseForwardedHeaders = true);
```

**Comment by br3nt** [comment]
Ok, so it seems that the docs were were updated between release v1.0.0-preview.3 and commit 9fc7391f.  That was really confusing.

Is it possible to do another release with those docs updates??  Maybe at 9fc7391f??  Though, it does look like there are some minor non-doc related changes between  v1.0.0-preview.3 and 9fc7391f.

**Comment by twsouthwick** [comment]
Yes, a new release is being planned in the near future. If you want to get the docs for the release you are using, please go to the tag for that release. Once we get a v1, things like that shouldn't change, but things are in flux for now.

**Comment by br3nt** [comment]
Thanks for the response.  I was on the tag for that release (v1.0.0-preview.3).  The docs at that point don't match the API.  The docs were were progressively updated after the tag v1.0.0-preview.3, up until commit 9fc7391.
