### ISSUE TITLE
'RemoteAppSessionStateOptions' does not contain a definition for 'RemoteApp' and 'ApiKey'

### ISSUE THREAD

**Issue by br3nt** [dotnet/systemweb-adapters#200]
### Describe the bug

I am getting the following two error messages:

> 'RemoteAppSessionStateOptions' does not contain a definition for 'RemoteApp' and no accessible extension method 'RemoteApp' accepting a first argument of type 'RemoteAppSessionStateOptions' could be found (are you missing a using directive or an assembly reference?)

and

> 'RemoteAppSessionStateOptions' does not contain a definition for 'ApiKey' and no accessible extension method 'ApiKey' accepting a first argument of type 'RemoteAppSessionStateOptions' could be found (are you missing a using directive or an assembly reference?)

I am trying to follow along to these guides:
* https://github.com/dotnet/systemweb-adapters/blob/v1.0.0-preview.3/docs/session-state/remote-session.md
* https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/comment-page-2/#session-support

I am getting:

![image](https://user-images.githubusercontent.com/1089651/189802327-b6b83d23-ec21-44fa-8108-444663d7f8d5.png)

Maybe I'm missing a using statement, but the docs don't mention anything besides adding the Microsoft.AspNetCore.SystemWebAdapters.SessionState NuGet package which was already present from using the Microsoft Project Migrations extension, there's no code suggestions that a package has been found, and I haven't manually found one.

The following versions have been added:
* Microsoft.AspNetCore.SystemWebAdapters.SessionState - 1.0.0-preview.3.22370.2
* Microsoft.AspNetCore.SystemWebAdapters - 1.0.0-preview.3.22370.2

### To Reproduce

Described above.

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): ASP.NET MVC
- .NET Framework Version: 4.8
- Windows Version: 10

*ASP.NET Core Application*:
- Targeted .NET version: .NET 6.0
- .NET SDK version:

**Comment by br3nt** [comment]
Just looking at the commit history on the main branch, it seems this doc was updated after the release in commit 1ee4c893.

So, should the code actually look like this???:

```
builder.Services.AddSystemWebAdapters()
    .AddJsonSessionSerializer(options =>
    {
        // Serialization/deserialization requires each session key to be registered to a type
        // see: https://devblogs.microsoft.com/dotnet/incremental-asp-net-to-asp-net-core-migration/comment-page-2/#session-support
        // see: https://github.com/dotnet/systemweb-adapters/blob/v1.0.0-preview.3/docs/session-state/remote-session.md
    })
    .AddRemoteAppSession(options =>
    {
        // ???
    })
    .AddRemoteApp(options =>
    {
        // Provide the URL for the remote app that has enabled session querying
        options.RemoteAppUrl = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);

        // Provide a strong API key that will be used to authenticate the request on the remote app for querying the session
        options.ApiKey = "strong-api-key";
    });
```

**Comment by br3nt** [comment]
Same comment as https://github.com/dotnet/systemweb-adapters/issues/199#issuecomment-1244919035.  A release containing the updated docs would be useful.

**Comment by twsouthwick** [comment]
As noted in #199, a new release should happen soon. Remember to checkout the tag for the release you are using to ensure you're using the up-to-date docs

**Comment by br3nt** [comment]
Thanks for the response. I was on the tag for that release (v1.0.0-preview.3). The docs at that point don't match the API. The docs were were progressively updated after the tag v1.0.0-preview.3, up until commit 9fc7391f.

Just leaving this note in case other peeps have the same issue as me.

**Comment by twsouthwick** [comment]
Oh! Sorry about that. Good catch
