### ISSUE TITLE
500 (Internal Server Error) from RemoteAppSessionStateManager.GetSessionDataAsync()

### ISSUE THREAD

**Issue by br3nt** [dotnet/systemweb-adapters#201]
### Describe the bug

I am getting the following exception after setting up remote-session.

<pre>
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, SessionAttribute metadata)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, SessionAttribute metadata)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
</pre>

I am getting the following output in the Output window:

<pre>
System.Net.Http.HttpClient.ISessionManager.LogicalHandler: Information: Start processing HTTP request GET http://localhost:52187/systemweb-adapters/session
System.Net.Http.HttpClient.ISessionManager.ClientHandler: Information: Sending HTTP request GET http://localhost:52187/systemweb-adapters/session
System.Net.Http.HttpClient.ISessionManager.ClientHandler: Information: Received HTTP response headers after 19.7831ms - 500
System.Net.Http.HttpClient.ISessionManager.LogicalHandler: Information: End processing HTTP request after 23.1643ms - 500
Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager: Error: Unable to load remote session state for session qxpzgkyv122mmsbmrxqnsd23

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, SessionAttribute metadata)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, SessionAttribute metadata)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, SessionAttribute metadata)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
</pre>

I have confirmed the ApiKey is that same in both apps.

### To Reproduce

This is using version 1.0.0-preview.3.22370.2 of Microsoft.AspNetCore.SystemWebAdapters and Microsoft.AspNetCore.SystemWebAdapters.SessionState.  These are added to both the ASP.NET app and ASP.NET Core app.

In ASP.NET Core program.cs:

```c#
using Microsoft.AspNetCore.SystemWebAdapters;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddSystemWebAdapters()
    .AddJsonSessionSerializer(options =>
    {
        options.RegisterKey<string>("crumbs");
        options.RegisterKey<string>("language");
    })
    .AddRemoteAppSession()
    .AddRemoteApp(options =>
    {
        options.RemoteAppUrl = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
        options.ApiKey = builder.Configuration.GetValue<string>("ReverseProxy:RemoteApp:ApiKey");
    })
    .AddRemoteAppAuthentication(true)
    ;

builder.Services.AddReverseProxy().LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

builder.Services.AddControllersWithViews();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthorization();
app.UseSystemWebAdapters();

app.MapDefaultControllerRoute();
app.MapReverseProxy();

app.Run();
```

In ASP.NET global.asax.cs:

```c#
protected void Application_Start()
{
    SystemWebAdapterConfiguration
        .AddSystemWebAdapters(this)
        .AddProxySupport(options => options.UseForwardedHeaders = true)
        .AddRemoteApp(options =>
        {
            options.ApiKey = ConfigurationManager.AppSettings["ReverseProxy:RemoteApp:ApiKey"];
        })
        .AddRemoteAppAuthentication(options =>
        {
            //options.AuthenticationEndpointPath = "Account/Login";
        })
        .AddRemoteAppSession()
        .AddJsonSessionSerializer(options =>
        {
            options.RegisterKey<string>("crumbs");
            options.RegisterKey<string>("language");
        })
        .AddSessionSerializer(options =>
        {
        })
        ;
}
```

In ASP.NET Core app Controllers\UserInfoController.cs:

```C#
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SystemWebAdapters;

namespace LabWebPortalCore.Controllers;

public class UserInfoController : Controller
{
    //[Authorize]
    [Session]
    public IActionResult Index()
    {
        return View();
    }
}
```

### Exceptions (if any)

Details above.

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): ASP.MVC 
- .NET Framework Version: 4.8
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 6.0
- .NET SDK version:

**Comment by twsouthwick** [comment]
I haven't seen this nor can I repro it. We're about to release rc1 with a number of fixes. If it still repros after that, please let us know. It will be easier to diagnose things in rc1 as well (logging will be available to be hooked up on the framework side)

**Comment by br3nt** [comment]
Turns out the 500 error was because the Type I passed to `options.RegisterKey<string>("crumbs");` didn't match the serialized type for that session key.

I think I read somewhere that the newer API will have better error messages for this kind of thing.... or I could be mistaking it for the exceptions that will be raised if there are session keys that aren't mapped.

**Comment by twsouthwick** [comment]
Ah, yes, that should be easier to diagnose in rc1. I'll close this for now - please reopen if needed.

**Comment by tsi-kyle** [comment]
> I also ran into a similar error when the class i passed in didn't have a constructor w/ no arguments.
> 
> Error Message: Response status code does not indicate success: 400 (Bad Request).
> 
> StackTrace: at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.SetOrReleaseSessionData(ISessionState state, CancellationToken cancellationToken) at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteSessionState.CommitAsync(CancellationToken token) at Microsoft.AspNetCore.SystemWebAdapters.SessionLoadMiddleware.ManageStateAsync(HttpContext context, ISessionStateFeature feature) at Microsoft.AspNetCore.SystemWebAdapters.PreBufferRequestStreamMiddleware.InvokeAsync(HttpContext context) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)...

I also just figured out this same error is caused when the passed-in class has a property that is an interface instead of concrete type.

ex:

    public class SessionModel
    {
        public int Id { get; set; }
        public string MyProperty { get; set; }
        public ICustomObject CustomObject { get; set; }
    }
    
instead of:

    public class SessionModel
    {
        public int Id { get; set; }
        public string MyProperty { get; set; }
        public CustomObject CustomObject { get; set; }
    }

The one with an interface throws that error.
