### ISSUE TITLE
Migrate Controller/Class/View doesn't do anything

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/systemweb-adapters#212]
### Describe the bug
I installed the extension. Then I opened a solution that has a .NET 4.7.2 Web API project and selected the Migrate option. I opted to create a new project. It ran for a little bit, configured YARP, etc and then showed me the summary page.

I now have the option to migrate controller/class/view. However the dropdowns are all empty. The text says to migrate from Solution Explorer so I go to SE, select one of my controllers and then select 'Migrate Controller'. It does nothing. No messages, no spinning, nothing.

Going back to the summary screen it shows my .NET Framework version as `0 (NaN)` and my .NET Core version as `0 (NaN)`. The `Routes` section is just a vertical white line.

I created a new web API project (no MVC) and tried it on that version. It migrated the project as before. However when I go to migrate a controller the only ones that show up are those that derive from `Controller` which is MVC, not API. Hence none of the API controllers are available (which is what I am seeing in my original project).

### To Reproduce
1. Create a new .NET 4.7.2 ASP.NET Web (.NET Framework) application. Only enable Web API (no MVC).
2. Run the migration tool on the project.
3. In the summary go to `Migrate Controllers` and notice the API controller doesn't show up.
4. In Solution Explorer right click the API controller and migrate it. Nothing happens.

### Exceptions (if any)
None. It just doesn't do anything.

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
.NET 4.7.2 Web API (no MVC)
Windows 10

*ASP.NET Core Application*:
.NET 6.0 Web API

**Comment by abpiskunov** [comment]
Thanks for reporting the issue! We can repro it now and working on the fix.

**Comment by abpiskunov** [comment]
@mtaylorfsmb we could repro the case when controller is API controller and it is not doing anything. However you mentioned that when you right click on just a class it did not do anything also? Or when you open Migrate Class dialog from the Migrations page it did not have any classes in the list (or you meant no controllers in the list)?

**Comment by mtaylorfsmb** [comment]
@abpiskunov Sorry for the confusion. Yes, when you click `Migrate Controller` nothing shows up (presumably because it doesn't see any API controllers). `Migrate Class` shows all the types in the project correctly.

As an aside note that the migration UI says to use SE to select the controller/class/view you want to migrate. But when you do that on an API controller it just sends you back to the migration UI summary page. This is what I meant by it not doing anything from SE.

**Comment by abpiskunov** [comment]
@mtaylorfsmb thanks for clarification. Yes, that is what I see here too. Api controllers support is coming very soon.

**Comment by abpiskunov** [comment]
This was fixed and there is a new VSIX where we consolidated all upgrade related scenarios: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.upgradeassistant&ssr=false#overview
