### ISSUE TITLE
Consider supporting VirtualPathProvider and associated infrastructure

### ISSUE THREAD

**Issue by CZEMacLeod** [dotnet/systemweb-adapters#218]
## Summary

Consider supporting `VirtualPathProvider` and associated classes: `HostingEnvironment`, `VirtualFileBase`, `VirtualFile`, and `VirtualDirectory`.
In ASP.NET Core, support `VirtualPathProvider` as an `IFileProvider` to allow StaticFiles to use `VirtualPathProvider`s.
Wrap the `WebRootFileProvider` as a `VirtualPathProvider` as the root provider to replace the MapPath based provider.
Consider providing a package to allow using any `IFileProvider` as a `VirtualPathProvider` under `System.Web` to allow using `EmbeddedFileProvider` in legacy classes during cutover.

## Motivation and goals

This would allow migrating existing scenarios with embedded resources or other virtual files to ASP.NET Core using the adapters.
This would be a stepping-stone to allowing creating a compatible version of `Microsoft.AspNet.Web.Optimization` / `System.Web.Optimization` which would unlock scenarios for people using this technology.

## In scope

Various classes from `System.Web.Hosting` including 
- `System.Web.Hosting.HostingEnviroment` (at least the `VirtualPathProvider` and `RegisterVirtualPathProvider` members, although `Cache`, `ApplicationPhysicalPath`, and `ApplicationVirtualPath` map directly to equivalents in `HttpRuntime` that are already implemented.)
- VirtualFileBase
- VirtualFile
- VirtualDirectory
- VirtualPathProvider

Extension methods for ASP.NET Core to allow registering `VirtualPathProvider`s via DI instead of legacy methods.
A VirtualPathProvider to wrap any `IFileProvider` (This could actually be used in legacy Framework projects too, but would require an additional reference to `Microsoft.Extensions.FileProviders.Abstractions` in whichever project it would be in.)
An FileProvider to wrap the VirtualPathProvider chain to allow the StaticFiles middleware to server files from the VirtualPathProviders.

## Out of scope

It would be nice to include the IFileProvider VirtualPathProvider under FrameworkServices or in the main adapters, as this would allow migration from custom VPPs to the existing FileProviders, such as `Microsoft.Extensions.FileProviders.Embedded` but as this would result in additional dependencies, this can be out of scope. 

## Risks / unknowns

Moving the existing WebRootFileProvider behind a VirtualPathProvider and then wrapping that as a FileProvider would potentially cause a performance issue with StaticFiles, however this would apply to the original ASP.NET Framework application too, and it is likely that any VPP is already pretty optimized and uses appropriate caching mechanisms to ensure its optimal speed. This is of course an interim step, and as a developer would expect to migrate any custom VPPs to IFileProviders or to use an existing out-of-box provider. (This is one reason to include the option to wrap IFileProviders as VirtualPathProviders). 

## Examples

Example code for VirtualPathProviders can be found at [VirtualPathProvider](https://learn.microsoft.com/en-us/dotnet/api/system.web.hosting.virtualpathprovider?view=netframework-4.8), [VirtualFile](https://learn.microsoft.com/en-us/dotnet/api/system.web.hosting.virtualfile?view=netframework-4.8), and [VirtualDirectory ](https://learn.microsoft.com/en-us/dotnet/api/system.web.hosting.virtualdirectory?view=netframework-4.8)

Global.asax.cs code such as 
```cs
            SamplePathProvider sampleProvider = new SamplePathProvider();
            System.Web.Hosting.HostingEnvironment.RegisterVirtualPathProvider(sampleProvider);
```
would become
```cs
builder.Services.AddSystemWebAdapters()
    .AddJsonSessionSerializer(options => ClassLibrary.RemoteServiceUtils.RegisterSessionKeys(options.KnownKeys))
    .AddVirtualPathProvider<ClassLibrary.SamplePathProvider>()
    .AddVirtualPathProvidersAsStaticFileProvider(options => options.ServeUnknownFileTypes = true)
```

If IHttpHandler and IHttpModule were implemented along with this, it would be possible to migrate the `Microsoft.AspNet.Web.Optimization` package that is regularly used in ASP.NET Framework applications without completely replacing the bundling system, making it easier to migrate MVC/Razor applications that use the package.

# Detailed design

See https://github.com/CZEMacLeod/systemweb-adapters/tree/czemacleod/virtualpathprovider for a rough implementation - this includes enhancements to Caching as required by the example that would probably deal with #26 too.

**Comment by twsouthwick** [comment]
@CZEMacLeod is there anything left from this after the additions you've made?

**Comment by CZEMacLeod** [comment]
@twsouthwick I don't think any of the VPP code has been added. While `VirtualPathProvider`s do tend to use some of the code `VirtualPathUtility` etc., they are not the same thing.
I've rebased and pushed my new branch as https://github.com/CZEMacLeod/systemweb-adapters/tree/czemacleod/vpp-1.1
Still cleaning up a few things here for things which were touched that shouldn't have been.

**Comment by CZEMacLeod** [comment]
@twsouthwick Actually found and fixed an issue with `Cache`/`CacheDependency` while doing this. I've also added a couple of tests to catch the problem.
I could spilt it out into a separate issue/PR if need be.
I think it must have been a copy/paste issue when I was creating my original branch for Cache in #276 for #26.

**Comment by twsouthwick** [comment]
@CZEMacLeod feel free to make a PR for this and we can discuss it there
