### ISSUE TITLE
Proxied Urls must point to a page, not a directory to work correctly

### ISSUE THREAD

**Issue by ahazelwood** [dotnet/systemweb-adapters#219]
### Describe the bug
I am attempting to use the Strangler Fig pattern with the yarp proxy serving as the entry-point into a IIS hosted asp.net webforms project.  Some of the paths point to directories **/dir** or **/dir/** which have a **default.aspx** or **default.cshtml** file in them.  Under IIS, the content from the file is returned correctly.  Using the yarp proxy, a error is returned.  Pointing the url at the underlying page **/dir/default** does work, but updating this in all of the locations where this is used is quite a bit.

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): WebForms, WebAPI, MVC
- .NET Framework Version: 4.8
- IIS Version:  8.0
- Windows Version: Windows Server 2019 Data Center

*ASP.NET Core Application*:
- Targeted .NET version: 6.0
- .NET SDK version: 6.0

**Comment by adityamandaleeka** [comment]
@ahazelwood Can you share the error you're seeing and how your proxy is configured (in launchsettings.json)?

Can you also check whether your PathBase is the same between the Framework and Core apps?

If you can create a GitHub repo that contains a minimal app that demonstrates the problem, that would be ideal.

**Comment by ahazelwood** [comment]
I created a local project where this did work correctly.  I will need to spend more time on my end to see if I can track down what may be preventing this in our production web forms instance.

**Comment by adityamandaleeka** [comment]
Ah, I see. Good luck figuring it out (and let us know if it ends up being something we should improve in documentation!).

**Comment by adityamandaleeka** [comment]
Closing this for now... feel free to open a new issue if you discover something is wrong in our code.
