### ISSUE TITLE
RemoteAppClientOptions.BackchannelHandler should be a factory method

### ISSUE THREAD

**Issue by duncansmart** [dotnet/systemweb-adapters#221]
I've called `AddRemoteAppClient` like so:

    services.AddSystemWebAdapters()
        .AddRemoteAppClient(options =>
        {
            options.BackchannelHandler = new MyBackChannelHandler();
        }

Where _BackChannelHandler_ is basically just a HttpClientHandler with some logging. But a few times during testing I've got an `ObjectDisposedException: cannot access a disposed object. object name: 'SocketsHttpHandler'.` in my HttpClientHandler's SendAsync:

![image](https://user-images.githubusercontent.com/576343/194495728-58f1a2fb-d58e-42bd-9633-376e7051350a.png)

(sorry for the screenshot, didn't grab the plain text)

On investigation It would appear that HttpClientHandler should **be a new instance every time**, otherwise you eventually hit this ObjectDisposedException. See dotnet/runtime#27610 for another example.

Therefore I suggest that RemoteAppClientOptions.BackchannelHandler be changed so that it's something like a `Func<HttpMessageHandler>` instead, so that AddRemoteAppClient can call it to get a new instance each time. 

For example:

https://github.com/dotnet/systemweb-adapters/blob/9921217743fea54e602d95e22ac48f7ca915d261/src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/RemoteAppClientExtensions.cs#L38

Change:

    if (options.BackchannelHandler is { } handler)
    {
        return handler;
    }

To something like:

    if (options.BackchannelHandlerFactory is { } factory)
    {
        return factory();
    }

**Comment by duncansmart** [comment]
Also, according to [the ConfigurePrimaryHttpMessageHandler docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler) remarks "_The configureHandler delegate should return a **new instance** of the message handler **each time it is invoked**_". 

My workaround for now is to "manually" build the services. Instead of using `AddRemoteAppClient` - I call `builder.Services.AddOptions<RemoteAppClientOptions>().Configure()` and `builder.Services.AddHttpClient("remote-client")` and in `ConfigurePrimaryHttpMessageHandler` I can return a new instance of my HttpClientHandler each time.

**Comment by mjrousos** [comment]
Thanks for the report and investigation, @duncansmart. As you noted, getting a singleton HttpMessageHandler for use with HttpClientFactory configuration is incorrect. In this case, though, the HTTP configuration from `RemoteAppClientOptions` doesn't really need to come from a factory since it won't change and we can just use a singleton HttpClient. I'll get a fix together and open a PR.
