### ISSUE TITLE
Missing HttpCapabilitiesBase.IsMobileDevice Property

### ISSUE THREAD

**Issue by johnLwith** [dotnet/systemweb-adapters#222]
## Summary

In System.Web.dll, we use [IsMobileDevice](https://learn.microsoft.com/en-us/dotnet/api/system.web.configuration.httpcapabilitiesbase.ismobiledevice?view=netframework-4.7.2) Property on `HttpBrowserCapabilities` class. but it looks missing in `Microsoft.AspNetCore.SystemWebAdapters` package.

In `BrowserCapabilitiesFactory.cs` looks assigned, see below fig.

![image](https://user-images.githubusercontent.com/10428889/194792442-68b3d6d9-73c1-4c0f-99f7-43c48a0cbbf9.png)

Is it changed to another place or not implemented?

**Comment by johnLwith** [comment]
https://github.com/dotnet/systemweb-adapters/pull/230

**Comment by twsouthwick** [comment]
Thanks @johnLwith
