### ISSUE TITLE
Support migrating class libraries to .NET Standard class libraries

### ISSUE THREAD

**Issue by danroth27** [dotnet/systemweb-adapters#225]
Currently we only support migrating class libraries to target .NET 6 or .NET 7:

![image](https://user-images.githubusercontent.com/1874516/195212252-a9f6ec98-e10f-4c4d-ad46-ef8e88ccf289.png)

We should support migrating class libraries to .NET Standard so that the migrated library can be shared with both the old and new projects.

@abpiskunov  @sayedihashimi

**Comment by danroth27** [comment]
Could we also use type forwarding to preserve type identity after migrating code to .NET ?

**Comment by abpiskunov** [comment]
Support for .NET Standard was added.
