### ISSUE TITLE
NameValueCollection pass through implementations don't implement HasKeys()

### ISSUE THREAD

**Issue by timmydo** [dotnet/systemweb-adapters#251]
### Describe the bug

NameValueCollection pass through implementations don't implement HasKeys(). `HasKeys()` is not marked virtual in `NameValueCollection`.

```
this.Request.Headers["Origin"] ==> "some value"
this.Request.Headers.HasKeys() ==> false
```

### To Reproduce

I found this code in our repo:

```
        private string GetOrigin()
        {
            return this.Request != null
                && this.Request.Headers != null
                && this.Request.Headers.HasKeys() ?
                this.Request.Headers[Constants.HeaderOrigin] : null;
        }
```

### Exceptions (if any)

No exceptions but existing code breaks

### Further technical details 

I recommend using BannedApiAnalyzers to track down usage and remove it. To fix the code I either removed it or changed code to use `.Count > 0`

related #244

**Comment by twsouthwick** [comment]
This may be a place we want to get some changes to `NameValueCollection` in the BCL. There are two options here:

1. Make `HasKeys()` virtual so we can override it
2. Change the default implementation from [checking the array length](https://source.dot.net/#System.Collections.Specialized/System/Collections/Specialized/NameObjectCollectionBase.cs,155) to looking at the `Count` property which would effectively do that same thing but get any derived behavior

I think (2) would be better as it seems weird that you can override count, but it's not being used for this. Not sure about risk, but changes to these types have a very high bar.

**Comment by adityamandaleeka** [comment]
Triage: Yea, adding this to the BannedApiAnalyzer list seems like a good idea.

Based on what we've seen, many uses of the `HasKeys()` function seem to be unnecessary, and in places where it's actually needed, `.Count > 0` is a good alternative as @timmydo noted above.

**Comment by adityamandaleeka** [comment]
Closing this issue, I'll mention it in #244 so we include this when we publish a recommended list for use with the BannedApiAnalyzer.

**Comment by timmydo** [comment]
Just to add a note: `.Count > 0` is only a good alternative if the NVC is used for headers and maybe sometimes query parameters. We have some people that implemented a 'ValuesCollection' by adding(null, value) to the NVC, and `.Count` is zero because Count only counts non-null entries. So, `HasKeys()` is closer to `.AllKeys.Any(k => k != null))`
