### ISSUE TITLE
Consider supporting cache dependencies

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#26]
Currently the Cache implementation exposes `CacheDepenendency` but cannot be constructed or used at the moment. This was used in framework to tie a cache entry to be updated/removed when some dependency changed. The default implementation watched for changes in files/directories. See https://docs.microsoft.com/en-us/dotnet/api/system.web.caching.cachedependency for details

**Comment by adityamandaleeka** [comment]
Let's wait for more feedback/requests for this for now.

**Comment by CZEMacLeod** [comment]
I have done an implementation of `CacheDependency` that is available [here](https://github.com/CZEMacLeod/systemweb-adapters/tree/czemacleod/cache).
I haven't added tests yet, but can look into what tests can be done if you want to add the code.
I have tested it with 'real' code though and it works as intended.

**Comment by joperezr** [comment]
Hey @CZEMacLeod we are currently checking what should be considered as part of our next release (1.1). Would you be interested in contributing the implementation you have?

**Comment by CZEMacLeod** [comment]
@joperezr Yeah - The implementation I've done is certainly available to be added as part of 1.1.
I'd need to rebase on the current release, and fix any clashes etc. before I could do a PR for it, but the version I had did work as expected. 
I don't have any unit tests defined - but my use of it with a real project using caching worked as expected. I think I might need some help putting together sensible tests for it.

**Comment by joperezr** [comment]
That's great to hear and also I'm glad that you've validated that it works as expected in a real project. @twsouthwick would you be able to help with tests?

**Comment by twsouthwick** [comment]
This has been added
