### ISSUE TITLE
Confusing Documentation Regarding Authentication Needs Editing For Clarity

### ISSUE THREAD

**Issue by MH61Aus** [dotnet/systemweb-adapters#261]
**Issue**

This didn't really for in with any of the available templates, but I wasn't sure where else to go as there is no general discussion/support area in this repo. 

The [docs](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?view=aspnetcore-7.0) discuss remote authentication where the dotnet core app defers authentication to the dotnet framework app. However it doesn't discuss letting the dotnetcore app handle authentication. I'm not sure if this is because it is assumed that authentication will always be migrated last, but its not in my case.

**Scenario**
I'm trying to migrate an old app/spa that was designed using [Extjs/Sencha 3.4](https://docs.sencha.com/extjs/3.4.0/#!/api/Ext.Direct) and utilizes the [Ext-diect-mvc](https://github.com/elishnevsky/ext-direct-mvc) package so that all controllers inherit form the DirectController instead of the regular base controller. These "Direct" controller actions are consumed as if they were Web API controllers by other extjs/sencha apps of ours. So I can't just remove the dependency on the Direct Controller, as it'll break a bunch of API dependencies. And I've looked at migrating the Ext-direct-mvc source code myself, but honestly, I'm a bit lost as its response objects manipulate the httpContext and Core doesn't have a HttpContextBase, and apparently the SystemWebAdapters don't help with this.

So I'm trying to proceed with keeping the old UI and Direct controllers in the old project, replacing the data access with a new Web API, whilst slowly building out new screens that consume the Web API too. Login in the new App has been plugged into Duende Identity Server, and the new Web API secured by it. But the challenge is the dotnet framework app doesn't know anything about the login details. i.e. it doesn't have an auth token to pass to the API for access. 
I can get the dot net framework app to recognize the logged in user by having the identity server create a forms auth ticket, but this is not ideal, as it still lacks an auth ticket, and access to the claims returned on the identity token.

So I guess I need to know if what I'm trying to do is even possible. And if not, the docs should be updated to reflect some of the scenarios that are not possible, even if that is just to explicitly say that Authorization must be migrated last.

**Comment by olesakn** [comment]
Seconding this. There are details on how to wrap AspNetCore session but nothing on whether the same concept can be done with authentication. 

I already ported my auth to my Core application but cannot figure out how to get the IPrincipal to be passed on to the Framework application.

**Comment by adityamandaleeka** [comment]
@MH61Aus @olesakn Thanks for sharing your feedback. As you've pointed out, sharing authentication only depends on the ASP.NET app for authentication decisions currently. Doing it from the Core app is something we're considering and is being tracked in https://github.com/dotnet/systemweb-adapters/issues/109.

**Comment by adityamandaleeka** [comment]
Closing this issue in favor of #109
