### ISSUE TITLE
ASMX support

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/systemweb-adapters#263]
## Summary

Support ASMX web services in .NET 6+

## Motivation and goals

We have a ASMX web service that a third party is using. This project, which was previously unknown to us, now requires a bug fix, but it depends on other libraries that we've already upgraded for .NET 6. Rolling back would be challenging at this point. Some options appear to be

1. Upgrade ASMX project to use .NET 6
2. Rewrite the API layer and convince the 3rd party to change their client
3. Rewrite the API layer but have it work identically to the ASMX
4. Copy the old code dependencies, before they were updated to .NET Core, and have the ASMX use that (resulting in some code duplication).

## Risks / unknowns

I know very little about ASMX services, so I can't provide more info. I'm just trying to get out of a jam.

**Comment by mjrousos** [comment]
Supporting a whole framework like ASMX web services is out of scope, unfortunately. The System.Web adapters are more targeted at making sure specific APIs from System.Web work in ASP.NET Core and .NET Standard contexts.

In this case, if you need to upgrade an ASMX web service to .NET 6, you might want to consider using [CoreWCF](https://devblogs.microsoft.com/dotnet/corewcf-v1-released/), though that's still a non-trivial change. System.Web adapters could be used if, in your service's logic, you need to use specific System.Web APIs that weren't previously available on .NET 6/7. This would be option 1 or 3 from your list. 

Given that this service is apparently not updated very often, you may also want to consider staying on .NET Framework (which is still supported) and just using old versions of dependencies if possible or duplicating some code as described in your option 4.
