### ISSUE TITLE
HttpContext.Current.ApplicationInstance is not includded in the adapters

### ISSUE THREAD

**Issue by joperezr** [dotnet/systemweb-adapters#273]
In the process of updating another solution to .NET Standard 2.0 I have also found that the `HttpContext.Current.ApplicationInstance` isn't available in the adapters. Will this be added? Is it preferred that I open a separate issue asking about that?

_Originally posted by @g2petter in https://github.com/dotnet/systemweb-adapters/issues/262#issuecomment-1381416248_

**Comment by twsouthwick** [comment]
@g2petter what API off of `ApplicationInstance` are you using? I have a prototype of this API, but it's in the context of `IHttpModule` support. I'm interested in understanding also what your scenario is that you're using that API.

**Comment by twsouthwick** [comment]
This is added with 1.2 and module support
