### ISSUE TITLE
Add missing API: HttpResponse.Flush

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#279]
## Summary
 When I try the IHttpModule and HttpApplication in the adapter, I found that HttpResponse.Flush is used in my module(in Sharepoint Online) but it is not supported.

## Motivation and goals
HttpResponse.Flush is used in my module(in Sharepoint Online) but it is not supported. I wonder if there is plan to support the API.

## In scope
HttpResponse.Flush

## Usage example:
```
Response.StatusCode = 500;
Response.Clear();
Response.Flush();
Response.End();
```

**Comment by joperezr** [comment]
@twsouthwick mentioned that he has an implementation for this that has been shared. It will be good to get a confirmation to see if this works as expected.
