### ISSUE TITLE
Add Missing API: HttpContext.ClearError

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#280]
## Summary
 When I try the IHttpModule and HttpApplication in the adapter, I found that HttpContext.ClearError is used in my module(in Sharepoint Online) but it is not supported.

## Motivation and goals
HttpContext.ClearError is used in my module(in Sharepoint Online) but it is not supported. I wonder if there is plan to support the API.

## In scope
HttpContext.ClearError

## Usage example:
```
context.Response.Clear();
context.ClearError();
context.Response.Output.Write(" <div>error</div>" )
context.Response.End();
```

**Comment by joperezr** [comment]
Discussed during triage, seems like we could either make this one be a no-op
