### ISSUE TITLE
Add missing API for Browser

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#282]
## Summary
 When I try the IHttpModule and HttpApplication in the adapter, I found that some properties of HttpBrowserCapabilities are used in my module(in Sharepoint Online) but they are not supported.

## Motivation and goals
Some properties of HttpBrowserCapabilities are used in my module(in Sharepoint Online) but they are not supported. I wonder if there is plan to support the API.

## In scope
HttpBrowserCapabilities.Type
HttpBrowserCapabilities.this[]
HttpCapabilitiesBase.PreferredRequestEncoding

## Usage example:
HttpBrowserCapabilities.Type
```
String.IsNullOrEmpty(request.Browser.Type)
```

HttpBrowserCapabilities.this[]
```
context.Request.Browser["needsRedirect"]  is true
```

HttpCapabilitiesBase.PreferredRequestEncoding
```
context.Request.ContentEncoding = context.Request.Browser.PreferredRequestEncoding
```

**Comment by joperezr** [comment]
@twsouthwick mentioned that he has an implementation for this that has been shared. It will be good to get a confirmation to see if this works as expected. There is also the question of how much of Browser actually works.
