### ISSUE TITLE
request.Browser throw exception when there is no useragent

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#283]
### Describe the bug
When there is no useragent, request.Browser could return null. But it throws exception.

### To Reproduce

send a request without useragent in headers

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/9064823/217420279-d2800911-5698-4e06-8418-e37967166b74.png)

**Comment by joperezr** [comment]
This is a bug in the Browser implementation that @twsouthwick is working on. Will close this as a dupe of https://github.com/dotnet/systemweb-adapters/issues/282
