### ISSUE TITLE
We should adopt Yarp 2.0

### ISSUE THREAD

**Issue by joperezr** [dotnet/systemweb-adapters#291]
One of the main reasons we care about this is because Yarp 2.0 supports net7.0

This will involve:
- [ ] Update tooling
- [ ] Update to use map-forwarder
- [ ] Update config.

**Comment by Tratcher** [comment]
https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html
AddReverseProxy becomes `services.AddHttpForwarder();`
MapReverseProxy becomes `app.MapForwarder("/{**catch-all}", app.Configuration["ProxyTo"]);`
All of the config gets replaced by the top level key: "ProxyTo" : "https://localhost:10000/"
