### ISSUE TITLE
Unknown Session Key Exception

### ISSUE THREAD

**Issue by SuhailRajani18** [dotnet/systemweb-adapters#299]
I have added all my existing asp.net webforms session keys in both .net core startup and asp,net webfroms global.asax file.
However while running the file, its giving me "UnknownSessionKeyException: Unknown session keys" error.
I am adding the session keys as "options.KnownKeys.Add("UserApplicationId", typeof(int));"
Can anyone please help?

**Comment by twsouthwick** [comment]
Do you have a repro? From what you are sharing it seems that there may be a session key you are not aware of - do you have any code that you may not own that would be using session? The exception should be sharing missing key information.

If you would like to ignore session keys that are unknown, you can set `SessionSerializerOptions.ThrowOnUnknownSessionKey 
 = false`. This defaults to true on the .NET Core side and false on the .NET Framework side.

**Comment by luismauricedecastro** [comment]
Where in the code can I access this property? ThrowOnUnknownSessionKey

**Comment by twsouthwick** [comment]
When registering things into the service collection:

```csharp
builder.Services.AddSystemWebAdapters()
    .AddSessionSerializer(options =>
    {
        options.ThrowOnUnknownSessionKey = true;
    })
```

**Comment by luismauricedecastro** [comment]
Thanks for that. I am not getting the unknown session error anymore. Anyway still have trouble. Every time that I access the session object from my Asp.Net Core application (either reading or writing), session information is lost on the Asp.Net MVC app.

Here is my full program.cs
========================================

var builder = WebApplication.CreateBuilder(args);

var ProxyTo = builder.Configuration["ProxyTo"];
var RemoteAppApiKey = builder.Configuration["RemoteAppApiKey"];

builder.Services.AddSystemWebAdapters()
    .AddJsonSessionSerializer(options =>
    {
        options.RegisterKey<string>("DatabaseName");
    })
    .AddSessionSerializer(options =>
    {
        options.ThrowOnUnknownSessionKey = false;
    })
    .AddRemoteAppClient(options =>
    {
        options.RemoteAppUrl = new(ProxyTo);
        options.ApiKey = RemoteAppApiKey;
    })
    .AddSessionClient();

builder.Services.AddHttpForwarder();

// Add services to the container.
builder.Services.AddControllersWithViews();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthorization();
app.UseSystemWebAdapters();

app.MapDefaultControllerRoute()
    .RequireSystemWebAdapterSession(); // This enables session sharing on all controllers

app.MapForwarder("/{**catch-all}", ProxyTo)
    .Add(static builder => ((RouteEndpointBuilder)builder).Order = int.MaxValue);

app.Run();

**Comment by luismauricedecastro** [comment]
And here is the section on my Global.Asax Application_Start() on the Asp.Net MVC App that configs session sharing:

            //Configure .Net Core Session Sharing
            {
                var RemoteAppApiKey = ConfigurationManager.AppSettings["RemoteAppApiKey"];

                SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
                    .AddJsonSessionSerializer(options =>
                    {
                        options.RegisterKey<string>("DatabaseName");
                    })
                    .AddRemoteAppServer(options =>
                    {
                        options.ApiKey = RemoteAppApiKey;
                    })
                    .AddSessionServer();
            }

**Comment by lucaslorensetti** [comment]
I had the same problem, and I finally could make it work by checking multiple examples of how people are using SystemWebAdapters.

Here is the code of my ASP.NET Core startup class:
```
public void ConfigureServices(IServiceCollection services)
{
	  services
		.AddSystemWebAdapters()
		.AddJsonSessionSerializer(options =>
		{
			options.RegisterKey<string>("Example1");
			options.RegisterKey<int>("Example2");
		})
		.WrapAspNetCoreSession()
		.AddSessionSerializer()
		.AddRemoteAppClient(options =>
		{
			options.RemoteAppUrl = new(LegacyUrl);
			options.ApiKey = SessionApiKey;
		})
		.AddSessionClient()
		.AddAuthenticationClient(true);

	services.AddHttpForwarder();
	services.AddDistributedMemoryCache();

	services.AddHttpClient();
	services.AddHttpContextAccessor();

	services.AddCors(opt =>
	{
		opt.AddDefaultPolicy(builder =>
		{
			builder.AllowAnyOrigin()
				.AllowAnyHeader()
				.AllowAnyMethod();
		});
	});

	services.AddRouting();
	services.AddControllers().AddJsonOptions(opts => opts.JsonSerializerOptions.PropertyNamingPolicy = null);

	services.Configure<JsonOptions>(options =>
	{
		options.SerializerOptions.PropertyNameCaseInsensitive = true;
		options.SerializerOptions.PropertyNamingPolicy = null;

		options.SerializerOptions.WriteIndented
#if DEBUG
			= true;
#else
			= false;
#endif
	});

	// services.AddHereYourIoC();
	// services.AddHostedService<YourBackgroundService>();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}
	else
	{
		//app.UseExceptionHandler("/Error");
	}

	app.UseHttpsRedirection();
	app.UseRouting();
	app.UseSession();
	app.UseAuthorization();
	app.UseSystemWebAdapters();
	app.UseEndpoints(endpoints =>
	{
		endpoints
			.MapDefaultControllerRoute()
			.RequireSystemWebAdapterSession();

		endpoints
			.MapForwarder("/{**catch-all}", LegacyUrl)
			.Add(static builder => ((RouteEndpointBuilder) builder).Order = int.MaxValue);
	});
}
```

And here is the code of my ASP.NET WebForms global.asax class:
```
protected override void Application_Start(object sender, EventArgs e)
{
	SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
		.AddProxySupport(options =>
		{
			options.UseForwardedHeaders = true;
		})
		.AddJsonSessionSerializer(options =>
		{
			options.RegisterKey<string>("Example1");
			options.RegisterKey<int>("Example2");
		})
		.AddRemoteAppServer(options => options.ApiKey = SessionApiKey)
		.AddSessionServer()
		.AddAuthenticationServer();

	base.Application_Start(sender, e);
}
```

Keep in mind that the `SessionApiKey` needs to be a Guid of the same value in both projects.

**Comment by lucaslorensetti** [comment]
Another thing that also I noticed is when I was trying to register nullable primitives I got the Exception as well, for example: `.RegisterKey<int?>("Example1");`. So I'm avoiding using nullable primitives in Sessions.

Before I forget: remember to add the **set** keyword on getters, i.e.: `{ get; set; }` on properties of complex objects (classes, structs, records) that are stored in Sessions. Otherwise, the serializer will not be able to fill the properties' values. That took some of my time to figure out why one side was showing values and the other side was not.

**Comment by twsouthwick** [comment]
@luismauricedecastro Looks like your registration is a different between the two apps; on framework you are doing:

```csharp
options.RegisterKey<string>("DatabaseName");
```

while on ASP.NET Core you are doing:

```csharp
options.RegisterKey("DatabaseName");
```

Notice that you are not adding the `<string>` so the serializer is assuming it to just be an object.

@lucaslorensetti  I've created a new issue to track the nullable support. Thanks for raising that point!

**Comment by twsouthwick** [comment]
We haven't heard anything, so I'm closing this issue for. Please reopen if it's still an issue.
