### ISSUE TITLE
MvcCoreApp does not compile

### ISSUE THREAD

**Issue by martincostello** [dotnet/systemweb-adapters#30]
Building the repo locally, the `MvcCoreApp` project fails to compile if `Yarp.ReverseProxy` 1.1.0 is not already in the user's local NuGet package cache.

It appears that the package is not available in any of the configured NuGet package sources in AzDo.

https://github.com/dotnet/systemweb-adapters/blob/8d6c13dcd8dc16f16c3bd9a65e8a94c7f2ed5541/NuGet.config#L4-L9

Manually adding the package source below to `NuGet.config` and running `dotnet restore` resolves the issue.

```xml
<add key="NuGet" value="https://api.nuget.org/v3/index.json" />
```

**Comment by twsouthwick** [comment]
@Tratcher is there a feed we should be including? I saw this when it first got updated to 1.1.0, but then went away. I figured it had been added to one of these feeds, but apparently not.

**Comment by Tratcher** [comment]
It should now be added to the dotnet-public feed. Try it and let us know.

**Comment by martincostello** [comment]
Cleared my local package cache, and confirmed that `dotnet restore` works as expected.
