### ISSUE TITLE
Documentation for Remote Authentication is incorrect

### ISSUE THREAD

**Issue by davethieben** [dotnet/systemweb-adapters#302]
[on this page](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?view=aspnetcore-7.0#aspnet-app-configuration) the ASP.NET app configuration example has this:

```
SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
    .AddProxySupport(options => options.UseForwardedHeaders = true)
    .AddRemoteApp(options =>
    {
        options.ApiKey = ConfigurationManager.AppSettings["RemoteAppApiKey"];
    })
    .AddRemoteAppAuthentication();
```

but "AddRemoteAppAuthentication" doesn't appear to exist (anymore?). I had to do some digging and found the correct syntax is:

```
     .AddAuthenticationServer(options =>
                {
                    //options.AuthenticationEndpointPath = "/";
                });
```

Similar issue for the ASP.NET Core app example (next paragraph) has:

```
   .AddRemoteAppAuthentication(true);
```

but should be:

```
    .AddAuthenticationClient(true);
```

**Comment by twsouthwick** [comment]
Sorry about that - we did some renames and must have missed a few. I've submitted a fix for those docs: https://github.com/dotnet/AspNetCore.Docs/pull/28545
