### ISSUE TITLE
Custom ASP.NET identity becomes ClaimsIdentity in .NET Core app

### ISSUE THREAD

**Issue by sand-head** [dotnet/systemweb-adapters#303]
Howdy all, I've used the Upgrade Assistant and these libraries over the past couple of days to try and start upgrading an old web forms app using forms authentication to .NET 7. Everything's been really smooth thus far, but a hiccup I've run into is that we use an internal custom `IIdentity` implementation, which after serialization and deserialization, seems to become a `ClaimsIdentity` over in the client app. I can see the user's name and auth status (great!) but all custom properties seem to be gone in the wind (less great). This would be fine if I could move these properties over to claims on the server side before serialization, but #209 appears to be closed, and I couldn't see any issues covering custom claim serialization still open.

What would be the best way forward for me in this scenario? It would be challenging to change any aspect of our current identity implementation, as it is used across teams in multiple large monolithic frontends.

**Comment by twsouthwick** [comment]
We could address it via #209 as you point out, but you mentioned that you'd be fine moving it over to a claims. Do you need a custom IIdentity? On ASP.NET Core, only ClaimsIdentity is available.

A way around this is to write a custom `IHttpModule` that will convert you IIdentity to a ClaimsIdentity on the `PostAuthenticate` event. You could even register the module via the the adapters service collection. Here's an example:

```csharp
 protected void Application_Start(object sender, EventArgs e)
  {
      SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
          .AddRemoteAppServer(options =>
          {
              options.ApiKey = ConfigurationManager.AppSettings["RemoteApiKey"];
          })
          .Services.AddSingleton<IHttpModule, RewriteClaimsModule>();
  }

  private sealed class RewriteClaimsModule : IHttpModule
  {
      public void Dispose()
      {
      }

      public void Init(HttpApplication context)
      {
          context.PostAuthenticateRequest += (s, e) => RewriteClaims(((HttpApplication)s).Context);
      }

      private void RewriteClaims(HttpContext context)
      {
          // TODO: Rewrite claims here
      }
  }
```

The real question is, if you're able to change it to a ClaimsIdentity for the whole request then it will:

1. Work correctly for the serialization
2. Be a consistent API for when you get on core

**Comment by joperezr** [comment]
Closing this as out of scope for now. @sand-head feel free to reopen if you have any follow-up comments/questions.
