### ISSUE TITLE
SDK style .NET Framework projects only get .NET Upgrade Assistant "In-place project upgrade" option

### ISSUE THREAD

**Issue by CopyPasteRepeat** [dotnet/systemweb-adapters#306]
### Describe the bug
We are using a new SDK style startup project for our ASP.NET MVC application based on NET Framework 4.8.
and want to use the incremental migration tool with the new .NET Upgrade Assistant to incrementally migrate our application to ASP.NET Core 7 MVC.

After the release of the new .NET Upgrade Assistant on 2/15/2023, we now see the "Upgrade" option when right-clicking our startup project, which before didn't work at all. However, no "Incremental side-by-side" option is offered, only "In-place project upgrade" is available.

Is this planned and if so when can we expect it?

### To Reproduce

Here you can see a slimmed down version of our ASP.NET MVC application startup project using SDK style together with .NET Framework 4.8

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppConfig>Web.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <ProjectCapability Include="DotNetCoreWeb" />
    <ProjectCapability Include="SupportsSystemWeb" />
  </ItemGroup>
</Project>
```

### Further technical details 

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC
- .NET Framework Version: 4.8

*ASP.NET Core Application*:
- Targeted .NET version: 7

**Comment by joperezr** [comment]
cc: @antonfirsov seems like the upgrade assistant is not detecting that this project needs updating due to the fact that it is already an SDK project. We should fix that.

**Comment by abpiskunov** [comment]
This is fixed in coming release this week.

**Comment by CZEMacLeod** [comment]
This would also apply to projects using [MSBuild.SDK.SystemWeb](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb) which is a slightly more advanced version of the above project.

**Comment by abpiskunov** [comment]
Version of vsix with the fix pushed to the VS market place.
