### ISSUE TITLE
Add Support for HttpContext.RewritePath of 2 params and 4 params

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#315]
## Summary

The HttpContext in adapter only supports RewritePath(String). But there is also usage of RewritePath(String, Boolean) and RewritePath(String, String, String, Boolean).

## Motivation and goals

 RewritePath(String, Boolean) and RewritePath(String, String, String, Boolean) are used in SharePoint Online. But they are not supported in the adapter. I use the code below instead. 
```
// case1: 2 params 
// old one 
context.RewritePath( newFilePath + originalPathInfo, true);
 // my workaround
context.RewritePath(newFilePath + originalPathInfo)

// case2: 4 params 
// old one 
context.RewritePath( newFilePath, originalPathInfo, originalQueryString, true); 
// my workaround
context.RewritePath(newFilePath + originalPathInfo + "?" + originalQueryString)
```

I wonder if there is plan to support the API.

## In scope
Add support of `RewritePath(String, Boolean)` and `RewritePath(String, String, String, Boolean)`

## Examples
```
context.RewritePath( newFilePath + originalPathInfo, true);

context.RewritePath( newFilePath, originalPathInfo, originalQueryString, true); 
```

**Comment by twsouthwick** [comment]
Happy to take a PR for this. Here's what ASP.NET Framework is doing here: https://referencesource.microsoft.com/#System.Web/HttpContext.cs,e1239e4275e728f9. That's more to understand the importance of the parameters - the code won't be a drop in replacement :)
