### ISSUE TITLE
Issue of HttpApplication.GetVaryByCustomString

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#316]
## Summary

In SharePoint Online repo, we override the HttpApplication.GetVaryByCustomString. But adapter does not support it. I'm not expert here so I would like to know where the method is used in .NetFramework and if it is needed in ASP.Net Core Application. 

## Motivation and goals
HttpApplication.GetVaryByCustomString is not supported in the adapter. I'm not expert here so I would like to know what the method is and if it is needed in ASP.Net Core Application. 

## Examples
In SharePoint, we override the function like
```
public override sealed string GetVaryByCustomString(HttpContext context, string custom)
{
            StringBuilder sb = new StringBuilder();
            try
            {
                foreach( var delegatefunction in _delegatefunctions)
                {
                    sb.Append( delegatefunction (this, context, custom ) );
                }
            }
            return sb.ToString();
}
```

**Comment by twsouthwick** [comment]
I'm adding this into #314
