### ISSUE TITLE
Add Missing API:  "System.Web.Hosting.HostingEnvironment.SiteName" and "System.Web.Hosting.HostingEnvironment.ApplicationID"

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#317]
## Summary
We use `System.Web.Hosting.HostingEnvironment.SiteName` and `System.Web.Hosting.HostingEnvironment.ApplicationID` in SharePoint as key to search the target data object. But there is no implementation in adapters. I find that there are alternatives like IHostingEnvironment.ApplicationName, IWebHostEnvironment. But I don't know if it is an equal alternative (we use it as search key so it should be same)

## Motivation and goals

Add missing API  `System.Web.Hosting.HostingEnvironment.SiteName` and `System.Web.Hosting.HostingEnvironment.ApplicationID` to adapter

## Usage
Use SiteName to search
```
retval =null;
string sitename= System.Web.Hosting.HostingEnvironment.SiteName;
foreach (var service in _services)
{
    foreach (var app in service.Applications)
    {
        foreach (var setting in app.settings)
        {
            if (setting.sitename== sitename)
            {
                retval = app;
                break;
            }
        }
        if (retval != null)
            break;
    }
}
```

Use ApplicationID to search
```
string appIdStr= System.Web.Hosting.HostingEnvironment.ApplicationID;
 if (appIdStr!= null && appIdStr.StartsWith("pattern/", StringComparison.Ordinal))
{
         appIdStr= appIdStr.Substring(8, idlen);
         appId = Int32.Parse(appIdStr, NumberFormatInfo.InvariantInfo);
}
return appId;
```

**Comment by twsouthwick** [comment]
These values are probably coming from IIS somewhere. Can you identify if they are? If you were to set IHostingEvironment data to those values, would that be sufficient?

If you need the System.Web.Hosting.HostingEnvironment APIs, they'd follow the pattern we did for [HttpRuntime](https://github.com/dotnet/systemweb-adapters/blob/main/src/Microsoft.AspNetCore.SystemWebAdapters/HttpRuntime.cs) that internally it's an interface and exposes the static properties as System.Web did.

**Comment by joperezr** [comment]
This seems like a subset of https://github.com/dotnet/systemweb-adapters/issues/368. Closing this as a dupe for now.
