### ISSUE TITLE
Sharing Sessions between .NET Framework and ASP.NET Core app overwrites HttpContext.Current.Session

### ISSUE THREAD

**Issue by CopyPasteRepeat** [dotnet/systemweb-adapters#341]
### Describe the bug

Enabling shared Sessions between .NET Framework and ASP.NET Core app overwrites `HttpContext.Current.Session` on call of ASP.NET Core Controller action and causes loss of all Sessions which were initially set by .NET Framework app on both sides.

### To Reproduce

1. I call a Controller of my .NET Framework app and check `HttpContext.Current.Session.SessionID` which is for example "gjbgnexyo5zkavnvirgzf1px" and `HttpContext.Current.Session` contains a Session item named "Culture", which was set by NET Framework app
2. I call an ASP.NET Core Controller (see below) and check the `HttpContext.Current.Session.SessionID` again, which now has different value "y3fndk0nilq1evwktb4cz4ff" and `HttpContext.Current.Session` has no Session items at all.
3. I call a Controller of my .NET Framework app again and check `HttpContext.Current.Session.SessionID` which is now set to the value from .NET Core app "y3fndk0nilq1evwktb4cz4ff" and `HttpContext.Current.Session` has no Session items any more as well.

ASP.NET Core app seems to overwrite the Session object completely and that affects the .NET Framework app as well. What am I doing wrong?

Configuration on .NET Core side

```
builder.Services.AddSystemWebAdapters()
    .AddJsonSessionSerializer(options =>
    {
        options.RegisterKey<string>("Culture");
    })
    .AddRemoteAppClient(options =>
    {
        options.RemoteAppUrl = new (builder.Configuration["DotNetMigration:ProxyTo"]);
        options.ApiKey = builder.Configuration["DotNetMigration:RemoteAppApiKey"] ;
    })
    .AddAuthenticationClient(isDefaultScheme: true)
    .AddSessionClient();
```

Configuratin on .NET Framework side

```
SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
     .AddProxySupport(options => options.UseForwardedHeaders = true)
     .AddJsonSessionSerializer(options =>
     {
         options.RegisterKey<string>("Culture");
     })
     .AddRemoteAppServer(options =>
     {
         options.ApiKey = ConfigurationManager.AppSettings["DotNetMigration:RemoteAppApiKey"] ;
     })
     .AddAuthenticationServer()
     .AddSessionServer();
```

Called action of ASP.NET Core Controller

 ```
[Session]
public class PreviewController : Controller
{
    [Authorize]
    [Route("Preview")]
    public IActionResult SessionState()
    {
        object? sessionCulture = System.Web.HttpContext.Current?.Session?["Culture"];
       
        if (sessionCulture != null)
        {
            var cultureInfo = new CultureInfo(sessionCulture.ToString());
            ViewData["Culture"] = cultureInfo.DisplayName;
        }

        return View();
    }
}
```

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC
- .NET Framework Version: 4.8

*ASP.NET Core Application*:
- Targeted .NET version: .NET 7

**Comment by CopyPasteRepeat** [comment]
After solving some NuGet issues within the .NET Framwork app it is working now, I finally get the sessions from .NET Framework app.
I output some session values as a validation on a View in the .NET Core app, which renders the results. I currently can see the body of the View containing the session results but on the bottom of that View I get the following error message:
```
HttpRequestException: Response status code does not indicate success: 400 (No session ID found).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.SetOrReleaseSessionData(ISessionState state, CancellationToken cancellationToken)
Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteSessionState.CommitAsync(CancellationToken token)
Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, SessionAttribute metadata)
Microsoft.AspNetCore.SystemWebAdapters.PreBufferRequestStreamMiddleware.InvokeAsync(HttpContext context)
Microsoft.Extensions.DependencyInjection.RegisterAdapterFeaturesMiddleware.InvokeAsync(HttpContext context)
Microsoft.Extensions.DependencyInjection.RegisterAdapterFeaturesMiddleware.InvokeAsync(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by CopyPasteRepeat** [comment]
I forgot to set it on the server side as well. Now the error message is gone, but I'm logged out when I return to the .NET Framework app now. 
```
 SystemWebAdapterConfiguration.AddSystemWebAdapters(this)
      .AddSessionServe(options => options.CookieName = cookieName);
```

**Comment by twsouthwick** [comment]
@CopyPasteRepeat Glad you figured it out. Are there any remaining issues here, or can we close it?

**Comment by CopyPasteRepeat** [comment]
@twsouthwick everything is now working perfectly, so there are no more issues left. I will close the ticket. Thank you.
