### ISSUE TITLE
Add Missing API: HttpCapabilitiesBase.Cookies

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#365]
## Summary

provides the value if the browser supports cookies.

## Motivation and goals

HttpCapabilitiesBase.Cookies provides the value if the browser supports cookies. But it is not in adapters yet.

## In scope

HttpCapabilitiesBase.Cookies

## Examples
```C#
if (!context.Request.Browser.Cookies)
    return;
SetResponseCookie(context);
```

**Comment by twsouthwick** [comment]
Fixed in #366
