### ISSUE TITLE
Ask About HttpContext.SetSessionStateBehavior

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#371]
## Summary
Our repo uses HttpContext.SetSessionStateBehavior which are not supported by ASP.NetCore and this adapters.
I want to ask if there is equivalent  and if there is plan to add them to adapter.

## Motivation and goals
We need migrate code (an API in Sharepoint) to ASP.NetCore and we find that the APIs are not supported by ASP.NetCore.

## In scope
- HttpContext.SetSessionStateBehavior
- HttpContext.SessionStateBehavior

From [src code](https://referencesource.microsoft.com/#System.Web/State/SessionStateModule.cs,627), It seems that the property is used to decide whether to acquire session state. But in the adapter, the session state is gotten from the feature.
I wonder if `SetSessionStateBehavior` is still needed.

## Examples
Here is an example of `HttpContext.SetSessionStateBehavior`
```C#
if (IsDataAPI(context))
{
    context.SetSessionStateBehavior(System.Web.SessionState.SessionStateBehavior.Disabled);
}
```

**Comment by twsouthwick** [comment]
What's the context this is used in? We currently decide if session is enabled by the SessionAttribute as metadata on the endpoint. In order to enable this, we'll need a per-request flag that could be set and checked in the SessionMiddleware.

**Comment by Clounea** [comment]
@twsouthwick The context is that, for specific url pattern, We don't want to use session state.

The thing which makes it complex is that, we don't use the ASP.NetCore endpoint, we use Microsoft.Owin to process the endpoints and wrap them in ASP.NetCore. 

Do you have suggestions?

**Comment by twsouthwick** [comment]
@Clounea What I would recommend is to add a new feature:

```csharp
internal interface ISessionStateFeature
{
  SessionStateBehavior State { get; set; }
}
```

behavior should probably be:

1. If the state is set here, have it be surfaced
2. If no state is set via the feature, default to the existing endpoint metadata if it is available

The Sessionmiddleware will need to be updated to handle this change (i.e. use this feature rather than metadata)
