### ISSUE TITLE
Ask About HttpRequest.CurrentExecutionFilePath

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#372]
## Summary

Our repo uses HttpRequest.CurrentExecutionFilePath  which is not supported by ASP.NetCore and this adapters.
I want to ask if there is equivalent and if there is plan to add them to adapter.

## Motivation and goals

We need migrate code (an API in Sharepoint) to ASP.NetCore and we find that the APIs are not supported by ASP.NetCore.

## In scope

- HttpRequest.CurrentExecutionFilePath

From [document](https://learn.microsoft.com/en-us/dotnet/api/system.web.httprequest.currentexecutionfilepath?view=netframework-4.8.1), [CurrentExecutionFilePath](https://learn.microsoft.com/en-us/dotnet/api/system.web.httprequest.currentexecutionfilepath?view=netframework-4.8.1) returns the file path to the currently executing page handler. For redirect scenarios using [Execute](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.execute?view=netframework-4.8.1) and [Transfer](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.transfer?view=netframework-4.8.1) methods this means that the [CurrentExecutionFilePath](https://learn.microsoft.com/en-us/dotnet/api/system.web.httprequest.currentexecutionfilepath?view=netframework-4.8.1) property returns the path to the page redirected to (child page). However, when the client is redirected to another page, the [FilePath](https://learn.microsoft.com/en-us/dotnet/api/system.web.httprequest.filepath?view=netframework-4.8.1) property returns the path to the original page.

But in `HttpRequestInputStreamFeature.cs`, the `Rewrite` function shows that the FilePath is changed to the new path. There is no variable recording the original path.

I wonder that will adapters support it?

## Examples
```C#
bool isErrorPage = false;
if (context.Request.CurrentExecutionFilePath.EndsWith("Error.aspx"))
{
    isErrorPage = true;
}
```

**Comment by twsouthwick** [comment]
So, if I understand correctly, it should be the same as FilePath, except under conditions that we don't currently support? It could probably be added to IHttpRequestPathFeature and surfaced that way. If `Execute` or `Transfer` is supported, they could then override it.
