### ISSUE TITLE
Ask About HttpServerUtility.TransferRequest

### ISSUE THREAD

**Issue by Clounea** [dotnet/systemweb-adapters#377]
## Summary

Our repo uses `HttpServerUtility.TransferRequest` which is not supported by ASP.NetCore and this adapters.
I want to ask if there is equivalent and if there is plan to add them to adapter.

## Motivation and goals

We need migrate code (an API in Sharepoint) to ASP.NetCore and we find that the APIs are not supported by ASP.NetCore.

## In scope

`HttpServerUtility.TransferRequest`

From this [post](https://stackoverflow.com/questions/39693050/alternative-to-server-transfer-in-asp-net-core), it seems that there are several options.
Will adapters add this function?

## Examples
```C#
context.Server.TransferRequest(
    modifiedUri,
    true,
    null,
    context.Request.Headers);
```

**Comment by twsouthwick** [comment]
I took a look at how this works from an API, and looks like, everything gets funneled into `HttpServerUtility.Execute(string path, TextWriter writer, bool preserveForm)`.  It appears that there are a few ways that this may be made to work in core, but not really sure what the *best* way would be.

For now, adding something like the following:

```cs
public interface ITransferRequestFeature
{
  void Transfer(string path, TextWriter writer, bool preserveForm)
}
```

and hooking it up to the `HttpServerUtility` can be enabled that allows the actually transferring to be handled in some way (i.e. maybe a redirect could be the default, but could be swapped out with whatever is required)

**Comment by birojnayak** [comment]
@twsouthwick feel free to assign to me...

**Comment by joperezr** [comment]
[Triage]: Talked about this one in triage, and this might be difficult to achieve given it is really difficult to re-route requests in .NET Core. We could add the API and make it a no-op (Or throw PNSE) and marked as obsolete so the code compiles if that would be useful, but of course the idea would be to not call it at runtime.
