### ISSUE TITLE
HttpRuntime.Cache throws "System.InvalidOperationException: No runtime is currently available" in unit tests

### ISSUE THREAD

**Issue by afshinm** [dotnet/systemweb-adapters#401]
### Describe the bug

Any call to `HttpRuntime.Cache` in class libraries fail with the `System.InvalidOperationException: No runtime is currently available` exception:

```
Test method Portal.Tests.Data.ForumTest.DataSelector_HappyPath threw exception:
System.TypeInitializationException: The type initializer for 'Portal.Data.UserAgentMatch' threw an exception. --->
    System.InvalidOperationException: **No runtime is currently available**
    at System.Web.HttpRuntime.get_Current()
    at System.Web.HttpRuntime.get_Cache()
```

This probably because `.Cache` tries to access the `HostingEnvironmentAccessor` here https://github.com/dotnet/systemweb-adapters/blob/main/src/Microsoft.AspNetCore.SystemWebAdapters/HttpRuntime.cs#L20 which is not available in a unit test environment. In `System.Web`, the cache object [gets created at runtime](https://github.com/microsoft/referencesource/blob/master/System.Web/HttpRuntime.cs#L2794-L2815) if it's not available which explains why this is not happening in the .NET Framework tests.

### To Reproduce

Create a class library that calls `HttpRutime.Cache[key]` and test this method in a unit tests.

### Exceptions (if any)

```
Test method Portal.Tests.Data.ForumTest.DataSelector_HappyPath threw exception:
System.TypeInitializationException: The type initializer for 'Portal.Data.UserAgentMatch' threw an exception. --->
    System.InvalidOperationException: **No runtime is currently available**
    at System.Web.HttpRuntime.get_Current()
    at System.Web.HttpRuntime.get_Cache()
```

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC
- .NET Framework Version: 4.7.2
- IIS Version: 10
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 6
- .NET SDK version: 6

**Comment by afshinm** [comment]
I just opened a PR to show how this can be reproduced and discuss a potential fix https://github.com/dotnet/systemweb-adapters/pull/402

**Comment by twsouthwick** [comment]
Not sure if we need to make changes to the code, but rather add documentation. Using xunit test fixtures (which is what we do internally slightly differently), the following allows you to test:

```csharp
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Web.Hosting;

namespace TestProject1
{
    [CollectionDefinition(nameof(RuntimeTestMarker), DisableParallelization = true)]
    public class RuntimeTestMarker
    {
    }

    [Collection(nameof(RuntimeTestMarker))]
    public class RuntimeTests
    {
        public static async Task<IAsyncDisposable> EnableRuntimeAsync(CancellationToken token = default)
        {
            var host = await new HostBuilder()
               .ConfigureWebHost(webBuilder =>
               {
                   webBuilder
                       .UseTestServer(options =>
                       {
                           options.AllowSynchronousIO = true;
                       })
                       .ConfigureServices(services =>
                       {
                           services.AddRouting();
                           services.AddSystemWebAdapters();
                       })
                       .Configure(app =>
                       {
                           // No need to configure pipeline for tests
                       });
               })
               .StartAsync(token);

            return new HostDisposable(host);
        }

        private sealed class HostDisposable : IAsyncDisposable
        {
            private readonly IHost _host;

            public HostDisposable(IHost host)
            {
                _host = host;
            }

            public async ValueTask DisposeAsync()
            {
                await _host.StopAsync();
                _host.Dispose();
            }
        }

        [Fact]
        public async Task RuntimeEnabled()
        {
            await using (await EnableRuntimeAsync())
            {
                Assert.True(HostingEnvironment.IsHosted);
            }

            Assert.False(HostingEnvironment.IsHosted);
        }
    }
}
```

**Comment by afshinm** [comment]
@twsouthwick That seems like a good idea, too, but it probably requires a lot of changes to existing test classes. Let me try that out today and give you feedback.

**Comment by afshinm** [comment]
@twsouthwick Seems like the `SystemWebAdaptersOptions` is excluded here https://github.com/dotnet/systemweb-adapters/pull/389/files#diff-bc1e96f031aab9e01db74de5ca6c6cfde0ed05fd8eebaa064deae8c0ada12a62R14 -- I'm not able to import it.

**Comment by twsouthwick** [comment]
Yeah it's new - you'll need to use a ci build of 1.3 preview

**Comment by afshinm** [comment]
@twsouthwick Thanks for confirming. I actually tried it without the `SystemWebAdaptersOptions` bit but I still got the `No runtime is currently available` exception after trying to reference `HttpRuntime.Cache`. I'm going to debug this a bit more.

**Comment by afshinm** [comment]
@twsouthwick I just updated our package version to 1.3.0-ci build and I can confirm that the `EnableRuntimeAsync` works as expected in 1.3.0-ci, but with 1.2.0 (latest version) the `No runtime is currently available` exception occurs.

**Comment by twsouthwick** [comment]
If I remember correctly, before 1.3 it was tied to HttpContext.Current, and part of the change for 1.3 was to enable it outside of a request.

**Comment by afshinm** [comment]
@twsouthwick Ah, that actually makes sense then. 

I'm happy to either update the docs or add a test helper which would configure the `HostBuilder`, which one do you think makes more sense?

**Comment by twsouthwick** [comment]
I think docs would be a good choice for now. We don't have a test-specific package, and unless there's something specific we need, docs should suffice

**Comment by afshinm** [comment]
@twsouthwick Just opened a PR to update the README https://github.com/dotnet/systemweb-adapters/pull/406. I'm not sure if README is the best place to add this, I was thinking maybe this guide could also be updated https://learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?view=aspnetcore-7.0.

**Comment by twsouthwick** [comment]
I think I'd prefer a the docs if you can open a PR there. It probably makes sense to create a new page "Unit Testing" or something similar

**Comment by afshinm** [comment]
@twsouthwick can we close this issue now that https://github.com/dotnet/AspNetCore.Docs/pull/30537 is merged?
