### ISSUE TITLE
Migration Fails - System.TypeLoadException: Could not load type 'Microsoft.WebTools.Shared.FeatureDetection.FeatureContext' from assembly 'Microsoft.WebTools.Shared

### ISSUE THREAD

**Issue by slipgateio** [dotnet/systemweb-adapters#48]
Hey guys,

The migration seems to be failing via the extension.

System.TypeLoadException: Could not load type 'Microsoft.WebTools.Shared.FeatureDetection.FeatureContext' from assembly 'Microsoft.WebTools.Shared, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

![image](https://user-images.githubusercontent.com/46474465/170436833-cf1fb23d-5379-4cb2-9eb2-2a05fff802ee.png)

**Comment by slipgateio** [comment]
Also wanted to say, I am very happy you guys are working on this.

We've been looking at the migration for a long time, even though we have a very modern WebForms app, we've wanted a pathway to .NET 6+.

So thanks for doing this.

**Comment by stefangevaert** [comment]
Just installed the extension, and having the same issue.

**Comment by twsouthwick** [comment]
Thanks for the feedback. An update will be pushed out soon that should fix this

**Comment by slipgateio** [comment]
Working now! Thanks!
