### ISSUE TITLE
1.2.0 => 1.3.X `ISessionStateFeature` is not available

### ISSUE THREAD

**Issue by tbertenshaw** [dotnet/systemweb-adapters#482]
After upgrading to 1.3.0 all my tests based on WebApplicationFactory fail with the following error `ISessionStateFeature is not available`
I can see recently an issue WRT to this #455, and PR #463. However I am not using `SessionState` 

![image](https://github.com/dotnet/systemweb-adapters/assets/2010002/ef8ae9d0-a745-4d12-af05-85fa644a0642)

To clarify I get the same error with `1.3.0` and `1.3.2`

**Comment by twsouthwick** [comment]
Can you share a repro of how you are setting things up? The service registration/middleware setup is probably sufficient

**Comment by twsouthwick** [comment]
Closing due to no updates. Feel free to reopen if you're still hitting it with the requested information
