### ISSUE TITLE
Unable to disable buffering once enabled

### ISSUE THREAD

**Issue by TaoziZ03** [dotnet/systemweb-adapters#508]
## Summary

Hi, I am migrating a web to net core. The line 68 enable response buffering if `HttpApplication` events are needed. This disables our cache policy in later code.

https://github.com/dotnet/systemweb-adapters/blob/c2607beb66e73455591084f8d3b73dd6eff2bc81/src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/SystemWebAdaptersExtensions.cs#L59-L81

## Motivation and goals

Allow user code to manage response buffering feature.

## Risks / unknowns

Can anyone provide some insights for this design?

## Repro

```c#
builder.Services.AddSystemWebAdapters()
    .AddWrappedAspNetCoreSession()
    .AddHttpApplication<MyApp>(options =>
    {
        options.RegisterModule<MyModule>("Module1");
        options.RegisterModule<MyModule>("Module2");
        options.RegisterModule<MyModule>("Module3");
.......
    });

var app = builder.Build();

// Since HttpApplication events are needed, here will add `HttpApplicationMiddleware`.
app.UseSystemWebAdapters();

app.Use((context, next) =>
{
    // This will not success because `HttpApplicationMiddleware` will enable buffering.
    if(!ShouldBufferReponse(context.Request.Path))
        context.Features.Get<IHttpResponseBodyFeature>().DisableBuffering();
    return next();
});
```
Here is where updated the response buffering.
https://github.com/dotnet/systemweb-adapters/blob/c2607beb66e73455591084f8d3b73dd6eff2bc81/src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/HttpApplication/HttpApplicationMiddleware.cs#L18

**Comment by twsouthwick** [comment]
Can you share a repro of what you're trying to achieve?

**Comment by TaoziZ03** [comment]
Updated

**Comment by twsouthwick** [comment]
Would adding an API like the following help here?

```diff
public class SystemWebAdapterOptions
{
+  public Func<HttpContext, ValueTask<bool>> IsBufferingEnabled { get; set; }
}
```

which would default to true to maintain current behavior, but allow you to override if buffering should be enabled?

**Comment by twsouthwick** [comment]
Actually, it appears that the following just doesn't work right:

```csharp
ctx.Features.GetRequired<IHttpResponseBodyFeature>().DisableBuffering();
```

With that fixed, does your scenario become unblocked?

**Comment by TaoziZ03** [comment]
Left a comment in the PR. Let's discuss the details there.
