### ISSUE TITLE
PreSendRequestHeaders and PreSendRequestContent should be fired when content is being sent

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#514]
If buffering is disabled and something is written. The framework `HttpApplication` will short circuit the request pipeline and jump to `RequestNotification.SendReponse` and raise `PreSendRequestHeaders` and `PreSendRequestContent` events.
In comparison systemweb-adapter will skip all the next stages and send the response.

`HttpReponse.Flush()` will expliexplicitly set `RequestNotification = SendReponse`. The `StepManager` will execute it. Following is the callstack.
```
>	System.Web.dll!System.Web.HttpContext.CurrentNotification.set(System.Web.RequestNotification **value = SendResponse**) Line 993	C#
 	System.Web.dll!System.Web.HttpRuntime.ProcessRequestNotificationPrivate(System.Web.Hosting.IIS7WorkerRequest wr, System.Web.HttpContext context) Line 1374	C#
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags) Line 461	C#
 	System.Web.dll!System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(System.IntPtr rootedObjectsPointer, System.IntPtr nativeRequestContext, System.IntPtr moduleData, int flags) Line 386	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Web.dll!System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush() Line 1729	C#
 	System.Web.dll!System.Web.HttpResponse.Flush(bool finalFlush, bool async) Line 1238	C#
 	System.Web.dll!System.Web.HttpWriter.WriteFromStream(byte[] data, int offset, int size) Line 341	C#

```

_Originally posted by @TaoziZ03 in https://github.com/dotnet/systemweb-adapters/issues/509#issuecomment-2224873982_

**Comment by twsouthwick** [comment]
@taoziZ03 do you need PreSendRequestContent ? We don't currently have that event enabled. If you do, please create a separate issue for it.

**Comment by twsouthwick** [comment]
@TaoziZ03 I have an implementation that should support PreSendRequestContent if you need it here: https://github.com/dotnet/systemweb-adapters/pull/515

**Comment by TaoziZ03** [comment]
Thanks! Yes, I need that. 👍
