### ISSUE TITLE
When not buffering, flushing should cause `Response.End()` to be called

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/systemweb-adapters#518]
# Repro 
```
Response.HttpContext.Features.GetRequired<IHttpResponseBufferingFeature>().DisableBuffering();
...
// The response will be sent to client after this line
// Let's say current at `RequestNotification.ExecuteRequestHandler`
Reponse.Body.Write(....);

// But the rest of events will still be raised, like
// `RequestNotification.ReleaseRequestState` and so on.
```

# Expected behavior
Please consider to raise `IHttpResponseEndFeature.EndAsync()` or proper method together to align framework.
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Web/HttpWriter.cs#L1610

_Originally posted by @TaoziZ03 in https://github.com/dotnet/systemweb-adapters/issues/509#issuecomment-2229894358_

**Comment by twsouthwick** [comment]
When I run it on framework, those events are still raised:

```
BeginRequest
PreSendRequestHeaders
AuthenticateRequest
PostAuthenticateRequest
AuthorizeRequest
PostAuthorizeRequest
ResolveRequestCache
PostResolveRequestCache
MapRequestHandler
PostMapRequestHandler
AcquireRequestState
PostAcquireRequestState
PreRequestHandlerExecute
Hello world
PostRequestHandlerExecute
ReleaseRequestState
PostReleaseRequestState
UpdateRequestCache
PostUpdateRequestCache
LogRequest
PostLogRequest
EndRequest
```

Note the headers are sent early (and the content event isn't enabled in the pr you raised the issue on). Once everything is merged, we can see if it still repros.

@taoziz03 can you provide a working sample of what you're seeing on framework?

**Comment by TaoziZ03** [comment]
I tested locally with all related changes. Pinged you offline about the repro.

**Comment by TaoziZ03** [comment]
I did some further tests. Turns out the existing app doesn't register events after the post execute handler. I can verify the behavior is equal if all the events are registered. Sorry for the incorrect issue. Please close this one. Thanks!

**Comment by twsouthwick** [comment]
oh great! thanks for the follow up
