### ISSUE TITLE
Add support for migrating using Blazor

### ISSUE THREAD

**Issue by danroth27** [dotnet/systemweb-adapters#53]
[Cocoon](https://github.com/VisualReCode/Cocoon) Offers support for migrating ASP.NET projects using Blazor. This is appealing for ASP.NET Web Form developers that are used to a component-based event-driven programming model.

Cocoon does some clever things to enable migration with Blazor using the strangler-fig pattern, like collecting the routable components in the app so that the fallback to the ASP.NET app happens correctly.

**Comment by slipgateio** [comment]
I'd like to see Blazor added as well.

**Comment by Michelh91** [comment]
Yeah would be amazing if support to Blazor is added, fallback to page components not working now

**Comment by tbertenshaw** [comment]
Would be keen to see this!. Looking to migrate a .NET MVC/WebApi/Angular/AspNet Identity app hosted in Azure app Service, to blazor web assembly running in AKS

**Comment by gerneio** [comment]
Anyone successfully setup systemweb-adapters w/ Blazor? I know Cocoon has a sample using their tooling (as mentioned by @danroth27), however would be nice for the officially supported migration tooling to at least document a route for this, even if manual. Blazor is 100% our future and the only compelling reason for us migrate from web froms/framework to core.

**Comment by joperezr** [comment]
As part of this, we will want to also add a doc into the migration documentation [here](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?view=aspnetcore-7.0)

**Comment by joperezr** [comment]
related: https://github.com/dotnet/aspnetcore/issues/42003

**Comment by twsouthwick** [comment]
This will be a part of ASP.NET Core 8, so for now we've added documentation here to enable support in ASP.NET Core 6 & 7: https://github.com/dotnet/AspNetCore.Docs/pull/28535

**Comment by gerneio** [comment]
Very nice, thanks for getting this doc put together @twsouthwick!

Live link for others: [Enabling Blazor support with Yarp](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-7.0)
