### ISSUE TITLE
Readme refers to NuGet nightly builds that don't seem to exist

### ISSUE THREAD

**Issue by AndrewBennet** [dotnet/systemweb-adapters#537]
The [README.md](https://github.com/dotnet/systemweb-adapters/blob/main/README.md#set-up) describes how to set up a nuget.config to access nightly builds of this package:

> Optional for nightly adapter builds: Set up NuGet.config to point to the CI feed:
> ```<?xml version="1.0" encoding="utf-8"?>
> <configuration>
>  <packageSources>
>    
>    <clear />
>    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
>    <add key=".NET Libraries Daily" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json" />
>  </packageSources>
> </configuration>

But when configured, the feed does not seem to contain systemwebadapters nightly builds. Visiting the feed URL directly confirms this:  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json

Are the nightly builds still supported? Or have they moved elsewhere?

I wanted to get access to the nightly build in order to make use of https://github.com/dotnet/systemweb-adapters/pull/527

**Comment by twsouthwick** [comment]
have you selected the "Show pre-release packages"? I'm seeing the releases when I look at the feed

![image](https://github.com/user-attachments/assets/0bd755d0-a31f-4e0c-9d85-66af1b74b407)

Try version 2.0.0-preview1.24416.1

**Comment by AndrewBennet** [comment]
Ah, whoops, yes, I think I must have not checked "Show pre-release packages"? I see them now. Thanks!
