### ISSUE TITLE
Adding an ASP.NET Core migration project should not disrupt the existing ASP.NET app

### ISSUE THREAD

**Issue by danroth27** [dotnet/systemweb-adapters#54]
Currently, when you run the migration tool to add an ASP.NET Core project, the ASP.NET Core project contains routes that most likely disrupt existing routes in the ASP.NET app (like "/"). For example, if you start with a default ASP.NET MVC app and then run the migration tool, the app is now appears replaced by the ASP.NET Core app when you run it. Ideally, after running the migration tool the app still functions as it did previously without any disruption. I think this means the ASP.NET Core migration project should initially be empty of any initial endpoints. The user then adds the endpoints that they want to migrate.

**Comment by danroth27** [comment]
@abpiskunov @sayedihashimi

**Comment by abpiskunov** [comment]
Fixed in recent vsix PR.
