### ISSUE TITLE
System.Web not working in .NET 8 for a Visual Basic project

### ISSUE THREAD

**Issue by SadhvikMorla** [dotnet/systemweb-adapters#546]
When trying to Import and use System.Web for html controls in a visual basic project with .NET version upgraded to .NET 8, it doesn't work.
screenshot of some errors are attached for reference

![Screenshot 2024-09-23 795461](https://github.com/user-attachments/assets/8e6bf0a8-f7d1-4db8-8f0e-691ff78f93b3)
![Screenshot 2024-09-23 765727272](https://github.com/user-attachments/assets/ed12a22d-cef5-4a60-8714-7c4d4352d937)

**Comment by joperezr** [comment]
Thanks for logging this issue @SadhvikMorla. @twsouthwick is this just because those particular APIs aren't part of the adapters?

@SadhvikMorla could you share some minimal repro project of the issue so we can take a closer look? Also, did you happen to check if this is a problem specific to VB?
