### ISSUE TITLE
Migration tool doesn't save changes to ASP.NET Core project file that add the adapter libraries

### ISSUE THREAD

**Issue by danroth27** [dotnet/systemweb-adapters#55]
When you run the migration tool on an ASP.NET project it creates a new ASP.NET Core project and then adds the adapter libraries and YARP packages to that project. However, the changes to the ASP.NET Core project file to add the package references aren't saved to disk.

Repro steps:
- Create a new ASP.NET MVC project
- Run "Migrate project" on the ASP.NET project
- Open the generated ASP.NET Core project file in Notepad (not VS)

Expected results:
- The project file has the adapter libraries and YARP project references

Actual results:
- VS added the packages references (you can see them in VS) but didn't save them to disk
- If you immediate try to close the solution after running the migration tool without running, building, or saving anything, then VS will complain that the ASP.NET Core project file has changes that need to be saved
 
Workaround:
- Click Save All to persist the added package references

@abpiskunov

**Comment by abpiskunov** [comment]
Fixed in recent vsix PR.

**Comment by abpiskunov** [comment]
Fixed in recent vsix PR.
