### ISSUE TITLE
Is not JSON serialization of the session state to limiting?

### ISSUE THREAD

**Issue by TPIvan** [dotnet/systemweb-adapters#57]
When ASP.NET session is using out of process storage the binary serialization is used as far as I know. I understand that binary serialization is very picky but with JSON serialization I am concerned about preserving internal state without any public representation.

I have done a test with [System.Web.Script.Serialization.JavaScriptSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.web.script.serialization.javascriptserializer?view=netframework-4.8) and adding parameter less constructor was required and private only field was lost in serialization/deserialization. 

Binary serializer also supports the [IDeserializationCallback Interface](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.ideserializationcallback?view=netframework-4.7.2) to enable the object recover from a serialized state. I wonder whether this interface used when deserializing objects.

I our company we have a rather large (~250 forms) Webforms application which is to be transformed in coming years.  Side by side migration library could be a great help.

**Comment by twsouthwick** [comment]
Yup - I have a pr (#51) that will allow you to control the serialization of a key on a much more granular level. That way, you can identify the best serialization technology you want to use.

The binary formatter used in framework is being deprecated in ASP.NET Core (https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete), so a different technology would be needed here.

**Comment by twsouthwick** [comment]
@TPIvan You can now customize it however you want with `ISessionKeySerializer`. We're still providing a default json one, but this will be the extensibility point you'll want to look at. If you have types that require special knowledge to serialize/deserialize, you'll have to manage that there.
