### ISSUE TITLE
Document how to deploy while migrating

### ISSUE THREAD

**Issue by slipgate-io** [dotnet/systemweb-adapters#65]
Hey all,

A question - how do I actually deploy this to something like Azure App Services. Do I need 2 web apps? I am guessing I can't just run a .NET6 app and its all going to work?

**Comment by twsouthwick** [comment]
Yes, you'd need to web apps (but could use the same app service). Each app would be deployed separately and could be versioned separately as needed - it's effectively a 2-service microservice at this point.

We'll be updating the docs to describe deployment at some point before preview.

**Comment by albertkohl-monotek** [comment]
i'd be interested in this too. we got the app working in visual studio for debug, but we need to deploy to an iis box.
i got both site working by themselves, i just cant figure out how to get the core site to route requests to the asp.net site.

any guidance or docs would be appreciated!

**Comment by jwoodcook** [comment]
#following, still following... We need to deploy to an Azure App Service and cannot find related info. Can YARP and [systemweb-adapters](https://github.com/dotnet/systemweb-adapters/) support 2 different App Services, or is there another way we should be trying?

**Comment by jwoodcook** [comment]
Has anyone deployed anything yet? Does anyone know where we would place the YARP config variable `ReverseProxy__Clusters__fallbackCluster__Destinations__fallbackApp__Address` in Azure deployments? I can create a separate question, if that's needed, but there seems to be NO deployment guidance at all, but I've got 2 Azure App Services all ready for this [systemweb-adapters](https://github.com/dotnet/systemweb-adapters) and I really need #help #assist #boost

**Comment by twsouthwick** [comment]
> Does anyone know where we would place the YARP config variable

Configuration would follow the normal app service configuration pattern. Please see the documentation here https://docs.microsoft.com/en-us/azure/app-service/configure-common.

**Comment by jwoodcook** [comment]
This is a typical YARP config, but Azure App Service does not seem to utilize it. Any tips on proper YARP & .NET 6 config?
```
  "ReverseProxy": {
    "Routes": {
      "fallbackRoute": {
        "ClusterId": "fallbackCluster",
        "Order": "1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
    "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": "https://apidev48.azurewebsites.net"
          }
        }
      }
    }
  }
```

**Comment by mjrousos** [comment]
I just ran through this scenario with App Service and it all worked as expected. I've put a summary of the steps I took here to hopefully get people unstuck and will work on adding a doc explaining the process for future reference.

## Steps to deploy to Azure App Service

1. Deploy both the .NET Framework and the .NET 6, each to their own Web App instance. In my case, I used to web apps in the same App Service Plan, but this shouldn't be necessary.
  1. ![image](https://user-images.githubusercontent.com/10077254/180281129-a90fd123-0b8f-4d95-a87c-a190ccca8ca3.png)
1. Edit the ASP.NET Core app's settings. This is done by choosing the 'Configuration' blade in the Portal (in the Settings section).
  1. I added a new application setting called `ReverseProxy__Clusters__fallbackCluster__Destinations__fallbackApp__Address` with a value of the ASP.NET app's root path (in my case, https://migrationdemonetfx.azurewebsites.net). Make sure to click 'save' after adding the app setting.
  1. ![image](https://user-images.githubusercontent.com/10077254/180281481-ad988eae-7e70-44e6-871e-c8bbea260607.png)
  1. ![image](https://user-images.githubusercontent.com/10077254/180281525-ef617149-bd49-43e2-811f-6a82e986a802.png)
1. Once that change was saved (which automatically restarted the ASP.NET Core app), I could navigate to the app and see that proxying to the ASP.NET app was working as expected. In this screenshot, notice that the URL is for my ASP.NET Core app, but the page that's shown is from the ASP.NET app (my Core app doesn't have a home/index route).
  1. ![image](https://user-images.githubusercontent.com/10077254/180281828-f1829101-f400-4825-bbdb-af8a6e355cfd.png)

**Comment by mikebrind** [comment]
Any advice on deploying to IIS? This works fine on my local machine (with Razor Pages instead of MVC controllers and views), but I can't seem to migrate to IIS successfully. I create two web sites in IIS, each with their own app pool and web.config, one for the Razor Pages app  and another for the legacy MVC 5 app, and set the fallbackApp Address to the MVC 5 site's URL. However, when requesting a URL that hasn't been migrated to Razor Pages, I get a 302 redirect to the fallback domain so the domain in the browser address bar is replaced with the legacy app's domain.

**Comment by mikebrind** [comment]
@mjrousos Thanks for coming back to me, Mike. I was using preview 2. Do you have any upgrade notes from preview 2 to 3? Only `RemoteServiceOptions` seems to have disappeared. This no longer compiles and I can't see any obvious alternatives:
```
builder.Services.AddSystemWebAdapters().AddRemoteAppAuthentication(true, options =>
{
    options.RemoteServiceOptions.RemoteAppUrl =
        new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
    options.RemoteServiceOptions.ApiKey = "_____";

});
```

**Comment by TheJayMann** [comment]
This is something that had me confused a bit when I was testing the fix to returnUrl.  At some point there was a change where remote options were separated from session and authentication and combined into remote options.  I believe you would need to change the above as follows.
```csharp
builder.Services.AddSystemWebAdapters().AddRemoteAppAuthentication(true).AddRemoteApp(options =>
{
    options.RemoteServiceOptions.RemoteAppUrl =
        new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
    options.RemoteServiceOptions.ApiKey = "_____";
});
```

**Comment by mikebrind** [comment]
@mjrousos I've updated to Preview 3 and the issue still occurs. A 302 redirect to the fallbackApp address for any endpoints not catered for in the .NET Core app.  I've also noticed that the user is not authenticated in the .NET Core app either.

SystemWebAdapters and reverse proxy config (thanks @TheJayMann):
```
builder.Services.AddSystemWebAdapters().AddRemoteAppAuthentication(true).AddRemoteApp(options =>
{
    options.RemoteAppUrl =
        new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
    options.ApiKey = "_____";
});
builder.Services.AddReverseProxy().LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));
```

.NET Core middleware:

```
app.UseStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseSystemWebAdapters();
app.MapRazorPages();
app.MapReverseProxy();
```

**Comment by mjrousos** [comment]
@mikebrind, as you noticed, the API for configuring remote app authentication has changed some between preview 2 and preview 3 (primarily so that remote app setup can be shared between remote auth and remote session, if needed) but the code you've shared here looks correct.

Have you also updated the ASP.NET (.NET Framework) app (as described [here](https://github.com/dotnet/systemweb-adapters/blob/main/docs/remote-authentication/remote-authentication.md#aspnet-app-configuration))?

In addition to updating the ASP.NET Core app, you need to call `AddRemoteApp` and `AddRemoteAppAuthentication` on the ASP.NET app, as well as making sure the [SystemWebAdapters module is registered in its web.config](https://github.com/dotnet/systemweb-adapters/blob/main/samples/MvcApp/Web.config#L133) (though, if you're using the [incremental migration tooling VSIX](https://devblogs.microsoft.com/dotnet/introducing-project-migrations-visual-studio-extension/) this should have happened automatically).

**Comment by adityamandaleeka** [comment]
@mikebrind It's not clear where the 302 could be coming from; YARP should handle the fallback without sending 302s.

If you could share a minimal app that demonstrates the problem and put it on a github repo for us to look at, that would be very helpful. Thanks!

**Comment by adityamandaleeka** [comment]
Moving this issue out of RC1 since it's not release-blocking. Still interested in understanding the problem above.

**Comment by mikebrind** [comment]
@mjrousos @adityamandaleeka Thanks for bearing with me. The issue was that I had not updated the .NET Framework app to use Preview 3 😬

After making those changes, I have it working as advertised on IIS now.

**Comment by mjrousos** [comment]
Awesome; glad to hear it's working now!
