### ISSUE TITLE
Virtual Application and Redirects

### ISSUE THREAD

**Issue by LodewijkSioen** [dotnet/systemweb-adapters#66]
### Describe the bug
Our application is installed on-premise in various locations. On some places the application is hosted in the root of an IIS Website and in other places it is an Application under the root. Our migration path using this project would be to do the switcheroo: the current application would be moved to a new WebSite and the new Core application would take it's original place so the URLs stay the same.

When the application is a Website in IIS, this works pefectly. However, as a Virtual Application the redirects fail because the proxied application ignores the fact that the public URL lives under a path.

### To Reproduce
Core Application: `https://localhost/application`
Webforms Application: `https://localhost:666/redirect.aspx` -> contains a redirect to `~/test.aspx`

Navigate to `https://localhost/application/redirect.aspx`
 -> Response: 302 to `https://localhost/test.aspx`

I would expect the Redirect to go to `https://localhost/application/test.aspx`

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): WebForms, WebApi, MVC (the whole shebang)
- .NET Framework Version: 4.8
- IIS Version: 10.0.22000.675
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 6.0
- .NET SDK version: 6.0.300

**Comment by twsouthwick** [comment]
@LodewijkSioen thanks for the bug. Can you provide the actual code you're using? There's potentially a few ways to initiate the flow you're describing. A minimum viable repro here would be helpful.

**Comment by LodewijkSioen** [comment]
I was actually busy creating one when something came up at work. I just pushed it here: https://github.com/LodewijkSioen/SystemWebAdaptersRedirect/

**Comment by twsouthwick** [comment]
@LodewijkSioen VirtualDirectories add in extra complexity. The challenge is that on the framework app, they are tightly integrated in with IIS and affect a lot of things like route generation/navigation/etc. Trying to override it in anyway causes problems. There is a workaround for this specific case (rewrite the Location header on the core app), but the central issue here is the difference in virtual directories.

Is there a reason you cannot deploy them to the same virtual directory but on different sites? That way the routes will be the same, but the port/url will be different (which is a much easier thing to address).

**Comment by LodewijkSioen** [comment]
Deploy to different sites but the same Virtual Directory is certainly possible. Just tested it and it works. This is probably the simplest solution, but just for completeness, could you share how the workaround with the Location header rewrite would look like?

**Comment by twsouthwick** [comment]
@LodewijkSioen for this specific instance, the following works (although I'd want to optimize it a bit more for production use):

```csharp
app.Use(async (ctx, next) =>
{
   await next();

   if (ctx.Response.StatusCode == 302 &&
       ctx.Response.Headers.Location is { } location)
   {
       if (ctx.Request.PathBase is { HasValue: true } pathBase)
       {
           // TODO: probably want a more optimized for prod
           var locations = location.Select(l => pathBase.Add(l).ToString()).ToArray();

           ctx.Response.Headers.Location = new Microsoft.Extensions.Primitives.StringValues(locations);
       }
   }
});
```
