### ISSUE TITLE
An unhandled exception occurred while processing the request

### ISSUE THREAD

**Issue by jbennink** [dotnet/systemweb-adapters#67]
### Describe the bug
When using Sessionstate I get the above error injected into the page where I access a session variable. It seems to go away when I don't use the sessionstate, remove the [Session] attribute from the controller for that page (and the nobviously session values are not available)

### To Reproduce
Just start the the app and go to a page that has [Session] added to the controller. See: [repro github repo](https://github.com/jbennink/systemweb-adapters-repro-issue-67.git)

### Exceptions (if any)
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.SetOrReleaseSessionData(ISessionState state, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteSessionState.CommitAsync(CancellationToken token)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, ISessionMetadata metadata)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, ISessionMetadata metadata)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): Webforms
- .NET Framework Version: net48
- IIS Version: IISExpress included with VS2022 
- Windows Version: Windows 11 Pro 21H2 22000.675

*ASP.NET Core Application*:
- Targeted .NET version: net6.0
- .NET SDK version: 6.0.300
- NET runtime version: 6.0.5

**Comment by twsouthwick** [comment]
We haven't seen that on IISExpress (we use that for testing) before. It's interesting that it looks like it is able to retrieve it and is failing when committing.  I've cloned your repro and see the same issue. I'll take a look and update when I figure out what the issue is

**Comment by twsouthwick** [comment]
I've tracked it down to needing the following handlers set:

```xml
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
```

This is added by the MVC templates, but I'm not sure exactly what it does. We can update the nuget package to add this if needed, but I'd like to understand why.

@Tratcher @davidfowl  any thoughts here?

**Comment by Tratcher** [comment]
I recall it has something to do with converting `/foo` to `/foo.aspx` before routing kicks in. What route is the session client requesting, and what's actually registered in the destination app?

**Comment by twsouthwick** [comment]
The default path is `/systemweb-adapters/session`. A `GET` works just fine, but the `PUT` fails without that handler
