### ISSUE TITLE
IIS + UseForwardedHeaders + System.Web.HttpContext.Current.Request.Url

### ISSUE THREAD

**Issue by nunomiguelsilvagoncalves** [dotnet/systemweb-adapters#80]
I created a brand new MVC .Net Framework App.

Then i used the Microsoft Project Migration Extension to create a new .Net Core App.

Changed the .Net Framework App to add

protected void Application_Start()
        {
...
            this.Application.AddSystemWebAdapters()
                .AddProxySupport(options =>
                {
                    options.UseForwardedHeaders = true;
                });
        }

I run the app in IISExpress and when i check the System.Web.HttpContext.Current.Request.Url value in the .Net Framework i have the .Net core url.

Then i change the hosting of the apps to run in IIS. I create 2 Application with 2 different Pools

Now when i check the System.Web.HttpContext.Current.Request.Url i have the .Net Framework url.

Am i missing something?

Thx

**Comment by twsouthwick** [comment]
@nunomiguelsilvagoncalves I was able to reproduce it this way:

1. Set up SiteCore to be on port 80
2. Set up SiteFramework to be on port 5005 (not important)
3. Deploy sites to both of these and set up configuration
4. Accessing framework site via proxy shows it's on 5005. 

Is this the set up you're seeing? This is a definitely a bug, but want to verify that it is the right issue you're seeing.

**Comment by nunomiguelsilvagoncalves** [comment]
Yes.
It was something similar.
In my situation I had 2 applications inside port 80.
I realized that was the problem and created 2 sites in 2 different ports and now I am able to proceed with the migration.
thanks

**Comment by twsouthwick** [comment]
Great! Once this is merged in, should be fixed, then!
