### ISSUE TITLE
Add some missing APIs for HttpContext, HttpRequest and HttpResponse

### ISSUE THREAD

**Issue by Maples7** [dotnet/systemweb-adapters#91]
## Summary

Most primary APIs of HttpContext, HttpRequest and HttpResponse are provided, which is fantastic! And some missing APIs could be considered to be added to make this adapter more universal.

## Motivation and goals

Some missing APIs are frequently used for .NET Framework and adding them to the adapter will make the migration smoother and more doable for large projects.

## In scope

For HttpContext:
- [x] DisposeOnPipeline https://github.com/dotnet/systemweb-adapters/pull/88
- [ ] CurrentHandler https://github.com/dotnet/systemweb-adapters/issues/146
- [ ] CurrentNotification https://github.com/dotnet/systemweb-adapters/issues/146
- [ ] IsCustomErrorEnabled https://github.com/dotnet/systemweb-adapters/issues/152
- [x] IsDebuggingEnabled https://github.com/dotnet/systemweb-adapters/pull/106
- [ ] PreviousHandler https://github.com/dotnet/systemweb-adapters/issues/146
- [x] Timestamp https://github.com/dotnet/systemweb-adapters/pull/104
- [ ] GetGlobalResourceObject https://github.com/dotnet/systemweb-adapters/issues/23
- [ ] GetLocalResourceObject https://github.com/dotnet/systemweb-adapters/issues/23
- [ ] GetSection https://github.com/dotnet/systemweb-adapters/issues/23
- [ ] RewritePath https://github.com/dotnet/systemweb-adapters/pull/145
- [ ] SkipAuthorization https://github.com/dotnet/systemweb-adapters/issues/147
- [ ] SetSessionStateBehavior https://github.com/dotnet/systemweb-adapters/issues/147

For HttpRequest:
- [x] AcceptTypes https://github.com/dotnet/systemweb-adapters/pull/101
- [ ] ClientCertificate https://github.com/dotnet/systemweb-adapters/issues/148
- [ ] FilePath https://github.com/dotnet/systemweb-adapters/issues/149
- [x] Files https://github.com/dotnet/systemweb-adapters/pull/103
- [x] Item[String] https://github.com/dotnet/systemweb-adapters/pull/105
- [x] Params https://github.com/dotnet/systemweb-adapters/pull/105
- [ ] PathInfo https://github.com/dotnet/systemweb-adapters/issues/149
- [ ] PhysicalPath https://github.com/dotnet/systemweb-adapters/issues/149
- [ ] ReadEntityBodyMode https://github.com/dotnet/systemweb-adapters/issues/150
- [ ] RequestContext https://github.com/dotnet/systemweb-adapters/issues/151
- [x] SaveAs https://github.com/dotnet/systemweb-adapters/pull/135

For HttpResponse:
- [x] AppendCookie https://github.com/dotnet/systemweb-adapters/pull/102
- [ ] AppendToLog https://github.com/dotnet/systemweb-adapters/issues/153
- [ ] ApplyAppPathModifier https://github.com/dotnet/systemweb-adapters/issues/149
- [x] BinaryWrite https://github.com/dotnet/systemweb-adapters/pull/102
- [x] ClearHeaders https://github.com/dotnet/systemweb-adapters/pull/102
- [ ] BufferOutput https://github.com/dotnet/systemweb-adapters/issues/147
- [x] IsRequestBeingRedirected https://github.com/dotnet/systemweb-adapters/pull/102
- [x] SubStatusCode https://github.com/dotnet/systemweb-adapters/pull/102
- [x] RedirectPermanent https://github.com/dotnet/systemweb-adapters/pull/102
- [ ] Expires https://github.com/dotnet/systemweb-adapters/issues/155
- [ ] SuppressFormsAuthenticationRedirect https://github.com/dotnet/systemweb-adapters/issues/154
- [x] TransmitFile https://github.com/dotnet/systemweb-adapters/pull/102
- [x] WriteFile https://github.com/dotnet/systemweb-adapters/pull/102
- [ ] WriteSubstitution

## Risks / unknowns

I can imagine not all of them make sense for ASP.NET Core, or fit .NET Core's design philosophy, or are easy to implement.

## Examples

More APIs covered, more large projects could be benefited.

**Comment by twsouthwick** [comment]
After looking into these APIs, some are definitely doable while others are on the harder side and some others are probably not something we can really mimic.

**HttpContext**

We should probably do:

- [ ] RewritePath
- [ ] Timestamp
- [ ] IsDebuggingEnabled (probably could check if it is production or not)
- [ ] GetSection (although we'd need to explore how the configuration would be used here)

The following are very much tied to IIS. ASP.NET Core does not have a concept of handlers, the SkipAuthorization is tied to IIS authorization, and the SetSessionStateBehavior would only be used in IHttpModules I think

- [ ] CurrentHandler
- [ ] CurrentNotification
- [ ] IsCustomErrorEnabled
- [ ] PreviousHandler
- [ ] GetGlobalResourceObject
- [ ] GetLocalResourceObject
- [ ] SkipAuthorization
- [ ] SetSessionStateBehavior

**HttpRequest**

We should probably do:

- [ ] AcceptTypes
- [ ] FilePath
- [ ] Files
- [ ] Item[String]
- [ ] Params
- [ ] PathInfo
- [ ] ReadEntityBodyMode
- [ ] SaveAs

These may be harder, but possible:
- [ ] RequestContext
- [ ] ClientCertificate
- [ ] PhysicalPath (this doesn't seem to map well with the abstracted file structure of core, but maybe there's an equivalent)

**HttpResponse**

We should probably do:

- [ ] AppendCookie
- [ ] BinaryWrite
- [ ] ClearHeaders
- [ ] IsRequestBeingRedirected
- [ ] RedirectPermanent
- [ ] TransmitFile
- [ ] WriteFile

These may be harder, but possible:
- [ ] AppendToLog
- [ ] ApplyAppPathModifier (appears to be used for cookieless sessions, which probably doesn't apply on core)
- [ ] BufferOutput (we currently require opt in to this with metadata, not sure if/how we should handle this)
- [ ] SubStatusCode (this is not transmitted to the client, but does end up in logs. This would require a change to https://github.com/dotnet/aspnetcore/blob/3f41ac1ea4b2932167f0a968cc562453a060c45c/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/managedexports.cpp#L161 to pass a substatus through)
- [ ] Expires (this would require HttpCachePolicy infrastructure to enable)
- [ ] SuppressFormsAuthenticationRedirect (this is a property that the FormsAuthenticationModule hooks into to rewrite 401 to 302)
- [ ] WriteSubstitution (this would need some of the HttpCachePolicy infrastructure to handle properly)

**Comment by adityamandaleeka** [comment]
Triage: we consider SubStatusCode to be obsolete so we wouldn't enable support for it without a strong business justification.

**Comment by twsouthwick** [comment]
Issues will be tracked in linked issues, so closing this larger issue.
