### ISSUE TITLE
Adapters: Add Playwright tests to verify output of core and framework

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/systemweb-adapters#94]

**Comment by HaoK** [comment]
Added two tests for FormsAuth + MVCApp, filed https://github.com/aspnet/Tooling-ManualTests/issues/1679 for the CTI test scenarios

**Comment by HaoK** [comment]
Resolved by https://github.com/aspnet/AspNetCore-ManualTests/pull/1639#pullrequestreview-1137849001
