### ISSUE TITLE
Add content to official docs

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/systemweb-adapters#98]
We should update the porting docs with content about this gradual migration process.

Notes:
- Probably want it to live somewhere in our porting docs here: https://learn.microsoft.com/en-us/dotnet/core/porting/
- Need to reconcile with https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-6.0
- Content will come from the docs we have in this repo (https://github.com/dotnet/systemweb-adapters/tree/main/docs). Reorganize as necessary.

**Comment by adityamandaleeka** [comment]
Should wait for API review to be done.

**Comment by adityamandaleeka** [comment]
We should also include https://github.com/dotnet/systemweb-adapters/issues/65#issuecomment-1191777391 when we do this.

**Comment by adityamandaleeka** [comment]
@Rick-Anderson Can you please help us get our content for these migration adapters/story onto the official docs? cc: @danroth27

**Comment by Rick-Anderson** [comment]
@adityamandaleeka  we can jump on this right after .NET 7 GA. Can I transfer this issue to https://github.com/dotnet/AspNetCore.Docs/issues ?

**Comment by adityamandaleeka** [comment]
A copy would be great just so we continue to track it on our 1.0 milestone. Thanks Rick!

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/27405

**Comment by adityamandaleeka** [comment]
@Rick-Anderson Do you have an estimate of how long it will take to get these docs ready? I know you said you'll start after .NET 7 GA but just curious when we can expect them to be ready (we're trying to plan out a release date for 1.0).

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Do you have an estimate of how long it will take to get these docs ready? I know you said you'll start after .NET 7 GA but just curious when we can expect them to be ready (we're trying to plan out a release date for 1.0).

I can get Incremental [ASP.NET to ASP.NET Core Migration](https://github.com/dotnet/systemweb-adapters/tree/main/docs) published in one day. With my other obligations, it might take two weeks to reconcile with [Migrate from ASP.NET to ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/) partially because [Migrate from ASP.NET to ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/) needs lots of updates.

**Comment by adityamandaleeka** [comment]
Thanks @Rick-Anderson. Any ETA on the move of https://github.com/dotnet/systemweb-adapters/tree/main/docs now that .NET 7 has GA'd? :smile:

Let us know if any questions arise during that move.

FWIW we're planning to release 1.0 GA when the docs are ready.

**Comment by Rick-Anderson** [comment]
> Thanks @Rick-Anderson. Any ETA on the move of https://github.com/dotnet/systemweb-adapters/tree/main/docs now that .NET 7 has GA'd? 😄

This week.

**Comment by Rick-Anderson** [comment]
@adityamandaleeka  can I get a few contacts? I'm replacing `External Traffic` with something more appropriate. Web requests?

**Comment by adityamandaleeka** [comment]
"Incoming requests" perhaps?

As for contacts, @mjrousos @twsouthwick @Tratcher @HaoK @danroth27 are all aware this docs move is happening and I'm sure they'd be happy to discuss stuff like that.

@abpiskunov and @sayedihashimi can answer things related to the VS extension side of the migration story.

**Comment by mjrousos** [comment]
Yep, incoming requests makes sense to me.

**Comment by adityamandaleeka** [comment]
> > Thanks @Rick-Anderson. Any ETA on the move of https://github.com/dotnet/systemweb-adapters/tree/main/docs now that .NET 7 has GA'd? 😄
> 
> This week.

@Rick-Anderson can we get an updated ETA on this? Still waiting on this for the 1.0 release.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson can we get an updated ETA on this? Still waiting on this for the 1.0 release.

Hopefully this week

**Comment by adityamandaleeka** [comment]
Most of this is done, still need to reconcile the new docs with https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-6.0

Also need to remove the docs from this repo since we don't want to maintain two copies.

**Comment by Rick-Anderson** [comment]
>Also need to remove the docs from this repo since we don't want to maintain two copies.

see #248
